### ISSUE TITLE
The migration failed due to local storage

### ISSUE THREAD

**Issue by Stanzilla** [vuejs/devtools-next#114]
With the new 7.0 release, the devtools bar at the bottom of my window no longer shows up, the old RC is fine.

**Comment by alexzhang1030** [comment]
Can you provide more information? I cannot reproduce

**Comment by Stanzilla** [comment]
Sure! What do you need? 

I don't have a SRE but here is the commit you could test with https://github.com/WeakAuras/WeakAuras-Companion/commit/f7677b682619c70ff9687fb6765d6b7ac133c03c

**Comment by alexzhang1030** [comment]
<img width="976" alt="image" src="https://github.com/vuejs/devtools-next/assets/49969959/faedcdd1-363c-4d38-a578-e9246595ed26">

Please try clearing the local storage associated with the developer tools and attempt the operation again. I just tested the devtools and it worked well.

**Comment by Stanzilla** [comment]
> <img alt="image" width="976" src="https://private-user-images.githubusercontent.com/49969959/293439900-faedcdd1-363c-4d38-a578-e9246595ed26.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5MDQwODEsIm5iZiI6MTcwMzkwMzc4MSwicGF0aCI6Ii80OTk2OTk1OS8yOTM0Mzk5MDAtZmFlZGNkZDEtMzYzYy00ZDM4LWE1NzgtZTkyNDY1OTVlZDI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMwVDAyMzYyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmZWY4M2I2YTE0MGI0MTBlNmVmZGUwMTRmMTc3YjYzN2JiODQzOGI5NWY3YmNkN2M1MDYzNmVmMjc4N2UxMjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.h9OAAreADGYFNNFSfBkYzBHt-id2qqI0lEgGMS-WVsM">
> Please try clearing the local storage associated with the developer tools and attempt the operation again. I just tested the devtools and it worked well.

that fixes it, thanks! there should probably be a migration step that cleans these? I had the issue on two different machines, both had the problematic local storage cache

**Comment by alexzhang1030** [comment]
Please be aware that the new devtools have rewritten all the code, and the functionality will differ compared to the old devtools. We will migrate gradually.

**Comment by alexzhang1030** [comment]
> > <img alt="image" width="976" src="https://private-user-images.githubusercontent.com/49969959/293439900-faedcdd1-363c-4d38-a578-e9246595ed26.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5MDQwODEsIm5iZiI6MTcwMzkwMzc4MSwicGF0aCI6Ii80OTk2OTk1OS8yOTM0Mzk5MDAtZmFlZGNkZDEtMzYzYy00ZDM4LWE1NzgtZTkyNDY1OTVlZDI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMwVDAyMzYyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmZWY4M2I2YTE0MGI0MTBlNmVmZGUwMTRmMTc3YjYzN2JiODQzOGI5NWY3YmNkN2M1MDYzNmVmMjc4N2UxMjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.h9OAAreADGYFNNFSfBkYzBHt-id2qqI0lEgGMS-WVsM">
> > Please try clearing the local storage associated with the developer tools and attempt the operation again. I just tested the devtools and it worked well.
> 
> that fixes it, thanks! there should probably be a migration step that cleans these? I had the issue on two different machines, both had the problematic local storage cache

Theoretically, this should be fine, but we will seek a method to automate the resolution of this issue if it indeed exists.

**Comment by alexzhang1030** [comment]
Thanks for your feedback 🙌, let's track it on

**Comment by webfansplz** [comment]
Close it for now and please feel free to comment or reopen the issue if someone also has the same issue.
