### ISSUE TITLE
Improve Component inspector target selection UX

### ISSUE THREAD

**Issue by yyx990803** [vuejs/devtools-next#118]
When clicking the "target" button to select components on the page to inspect:

<img width="314" alt="Screenshot 2023-12-30 at 5 12 31 PM" src="https://github.com/vuejs/devtools-next/assets/499550/053716e2-6626-4a2f-92a1-3d52a750fb52">

- The devtools should be minimized after clicking the button. Otherwise it covers components that need to be selected.
- When selecting components, the highlighting seems to be a bit off compared to when hovering over the component tree in the inspector, see video below:

https://github.com/vuejs/devtools-next/assets/499550/56415650-54e9-40d6-9f51-f799f9896ed0

**Comment by rupeshraj40** [comment]
hi
