### ISSUE TITLE
"Open in editor" doesn't work with VS Code + WSL

### ISSUE THREAD

**Issue by Deckluhm** [vuejs/devtools-next#125]
First, this new version of Vue DevTools looks really awesome for so many reasons so... thank you! 🙏 

I'm working on a project with 2 machines: one using Ubuntu, the other one with Windows 11 + WSL.
I installed the Vite plugin and it works fine on my Ubuntu machine but not on my Windows one.

I have the following error message when I try to open a component:
```
Could not open MyFile.vue in the editor.
```
My Vue server is running inside WSL but the app is displayed on Windows.

I suspect this is not specific to WSL but likely to any remote environment (since, from my understanding, this is how the [VS Code WSL extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl) works).

Tell me if you need any additional information!

**Comment by webfansplz** [comment]
Thank you for the feedback, can you follow the [document](https://github.com/webfansplz/vite-plugin-vue-inspector?tab=readme-ov-file#vs-code-with-wsl-windows) and try again?

**Comment by Deckluhm** [comment]
Thank you for the quick reply, it works perfectly 👌

Worth mentioning in the documentation imo (but you probably already planned that for later).

**Comment by webfansplz** [comment]
> Thank you for the quick reply, it works perfectly 👌
> 
> Worth mentioning in the documentation imo (but you probably already planned that for later).

Yeah, sure. I'll document it later.
