### ISSUE TITLE
Deserialize issue on editing the Pinia state property

### ISSUE THREAD

**Issue by Azurewarth0920** [vuejs/devtools-next#127]
It may also occur on other custom property.
The custom property is not been correctly deserialized on editing.

In the reproduction, the count property should be deserialized as native type number.
Reproduction:

https://github.com/vuejs/devtools-next/assets/22590005/23bea34e-e8d2-4c74-a53a-e9277809209b

**Comment by webfansplz** [comment]
Be related to #109
