### ISSUE TITLE
The key of nested object is displayed as a.b.c: value

### ISSUE THREAD

**Issue by Azurewarth0920** [vuejs/devtools-next#133]
It looks counterintuitive.

Is it a bug or feature?

<img width="417" alt="Screenshot 2024-01-03 at 9 21 41" src="https://github.com/vuejs/devtools-next/assets/22590005/f129d8de-4479-4e2c-9082-de0e0a8645c9">

**Comment by webfansplz** [comment]
Oh, it's a bug. PR Welcome if you're interested in it.
