### ISSUE TITLE
Use standalone mode

### ISSUE THREAD

**Issue by vallemar** [vuejs/devtools-next#141]
Hi, is it possible to use Standalone mode with webpack? 
I am trying to call .connect and the promise resolves but when doing console.log(devtools) I see that connect is false

**Comment by alexzhang1030** [comment]
Standalone mode is bundler-agnostic

All you need to do is add this `script` to your `index.html`, and open the page ;)

<img width="836" alt="image" src="https://github.com/vuejs/devtools-next/assets/49969959/57ef7561-e366-498f-ab64-fd44b2b15e6c">

**Comment by vallemar** [comment]
Hi @alexzhang1030 !  thanks! so there is something missing, when I try these changes https://github.com/nativescript-vue/nativescript-vue/pull/1074 the `.connect` promise is resolved but the status is as follows
```
  {
     "state": {
       "connected": false,
       "clientConnected": false,
       "appRecords": [],
       "activeAppRecord": null,
       "selectedComponentId": null,
       "pluginBuffer": [],
       "tabs": [],
       "commands": [],
       "vitePluginDetected": false,
       "activeAppRecordId": null
     },
     "context": {
       "appRecord": null,
       "api": null,
       "inspector": [],
       "timelineLayer": [],
       "routerInfo": {},
       "router": null,
       "activeInspectorTreeId": "",
       "componentPluginHookBuffer": []
     },
     "hook": {
       "on": {}
     },
     "api": null
   }
```

On the contrary, if global.document is undefined (by commenting this line https://github.com/nativescript-vue/nativescript-vue/blob/1d1a1540402d16f5097e2607cf9e91133af52829/devtools.js#L22) I get the following
```
  {
     "state": {
       "connected": false,
       "clientConnected": true, // THIS IS CONNECTED
       "appRecords": [],
       "activeAppRecord": null,
       "selectedComponentId": null,
       "pluginBuffer": [],
       "tabs": [],
       "commands": [],
       "vitePluginDetected": false,
       "activeAppRecordId": null
     },
     "context": {
       "appRecord": null,
       "api": null,
       "inspector": [],
       "timelineLayer": [],
       "routerInfo": {},
       "router": null,
       "activeInspectorTreeId": "",
       "componentPluginHookBuffer": []
     },
     "hook": {
       "on": {}
     },
     "api": null
   }
```

but the application remains in an intermediate state between waiting and the debug screen

<img width="804" alt="image" src="https://github.com/vuejs/devtools-next/assets/15719383/8f543402-179d-4fe6-9a30-a2a3f6f85b1b">

So, it seems that globalThis.global.document being undefined seems to do something else. Is there anything that xxx mode needs to work from`window` or `document`?

**Comment by alexzhang1030** [comment]
Probably need your help /cc @webfansplz

**Comment by webfansplz** [comment]
Hi @vallemar, so glad to see Nativescript is trying to integrate the devtools next, I want to help you support it. 

I haven't used Nativescript before, Is there any way to quickly debug it with [1074](https://github.com/nativescript-vue/nativescript-vue/pull/1074) locally? thank you.

**Comment by alexzhang1030** [comment]
I've tested a Vue3 + webpack project created by vue-cli, and
faced the same issue.

**Comment by alexzhang1030** [comment]
I'm not sure if this is related to ESM or CJS or Webpack, but it's a clue.

**Comment by vallemar** [comment]
> Hola@vallemarMe alegra mucho ver que NativeScript está intentando integrar las herramientas de desarrollo a continuación. Quiero ayudarlo a respaldarlo.
> 
> No he usado NativeScript antes. ¿Hay alguna forma de depurarlo rápidamente con https://github.com/nativescript-vue/nativescript-vue/pull/1074 localmente? gracias.

I think the only way is to install the nativescript development elements and run the sample application that has under the PR branch.

Here is the [documentation](https://docs.nativescript.org/setup/#local-setup) to install the setup. If you have any questions I can try to help you or you can join the NativeScript discord server, it may be faster.

Although if you have found the same thing with vuetify it may be faster to solve it with it

**Comment by webfansplz** [comment]
Hi @vallemar, you can try it again with:

- Upgrade to v7.0.6 
- Make sure to invoke devtools connect function before creating Vue App

**Comment by vallemar** [comment]
Hi @webfansplz ! For me this version still doesn't work with v7.0.6, would you have a vuetify sample?

I think we are loading vue-detools before the application, @rigor789 can you confirm this?

**Comment by webfansplz** [comment]
> Hi @webfansplz ! For me this version still doesn't work with v7.0.6, would you have a vuetify sample?
> 
> I think we are loading vue-detools before the application, @rigor789 can you confirm this?

Can you help me create a mini repo with Vuetify? thanks. 
In addition, not loading devtools before the application, but invoke devtools connect function before create Vue App.

**Comment by rigor789** [comment]
> Hi @webfansplz ! For me this version still doesn't work with v7.0.6, would you have a vuetify sample?
> 
> I think we are loading vue-detools before the application, @rigor789 can you confirm this?

We're loading it before the Vue app yes, and also calling `connect` before the main app is created/mounted.

@webfansplz how does the communication between the app and devtools work, I saw RPC in there, but I presume there's some kind of socket too, or just polling? Wonder if we're not making the actual connection (since we're not exactly in a web environment, we might need to polyfill something in addition).

**Comment by webfansplz** [comment]
> > Hi @webfansplz ! For me this version still doesn't work with v7.0.6, would you have a vuetify sample?
> > I think we are loading vue-detools before the application, @rigor789 can you confirm this?
> 
> We're loading it before the Vue app yes, and also calling `connect` before the main app is created/mounted.
> 
> @webfansplz how does the communication between the app and devtools work, I saw RPC in there, but I presume there's some kind of socket too, or just polling? Wonder if we're not making the actual connection (since we're not exactly in a web environment, we might need to polyfill something in addition).

The standalone mode uses socket, and it's the same as the old devtools implementation.

**Comment by rigor789** [comment]
Rebuilt `@vue/devtools-electron` without minifying so I can easily add some console logs, seems like the socket.io client does connect successfully, and events start going in/out.

The issue seems to be related to the devtools-hook being created after the custom renderer.

I was able to call in `createApp` (to delay the call) and that seems to have helped.
```ts
setDevtoolsHook(global.__VUE_DEVTOOLS_GLOBAL_HOOK__ as any, global);
```

![image](https://github.com/vuejs/devtools-next/assets/879060/6d5f640d-6fa7-4eb6-ad84-1d21067a7607)

Reconnects/initial connection seems to be an issue - have to reopen the app for the initial connection, and reconnecting the app doesn't work - will investigate that further later, but this is promising!

**Comment by webfansplz** [comment]
> Rebuilt `@vue/devtools-electron` without minifying so I can easily add some console logs, seems like the socket.io client does connect successfully, and events start going in/out.
> 
> The issue seems to be related to the devtools-hook being created after the custom renderer.
> 
> I was able to call in `createApp` (to delay the call) and that seems to have helped.
> 
> ```ts
> setDevtoolsHook(global.__VUE_DEVTOOLS_GLOBAL_HOOK__ as any, global);
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/879060/295244935-6d5f640d-6fa7-4eb6-ad84-1d21067a7607.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4OTczNjEsIm5iZiI6MTcwNDg5NzA2MSwicGF0aCI6Ii84NzkwNjAvMjk1MjQ0OTM1LTZkNWY2NDBkLTZmYTctNGViNi1hZDg0LTFkMjEwNjdhNzYwNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMFQxNDMxMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZmIxMTFmOTkwMjg1ZDRjOWQ4OTI3YmQ5OTEzNzg5OWZhMzY5ZmE3MDZhOWNhMjI0ZTliMGM4MDQ3N2E0OWUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CVws0NOoZhmotcIuRTty_Ayrr6t7PEKf7xhi7YfL6sg)
> 
> Reconnects/initial connection seems to be an issue - have to reopen the app for the initial connection, and reconnecting the app doesn't work - will investigate that further later, but this is promising!

Good catch ! I submitted a PR (#164) to resolve it. Can you try the `packages/vue-termui-playground/src/main.ts` setting (import devtools and call connect function before import and create vue), I'll find a better way to handle it if it also works forNativeScript.

**Comment by webfansplz** [comment]
Hi @vallemar @rigor789 , I believe this issue has been solved in 7.0.8, can you help me try it again:

```ts
// import before vue
import { devtools } from '@vue/devtools'
import '@vue/devtools/hook'

// connect before create vue app
devtools.connect('xxx','xxx')
```

**Comment by rigor789** [comment]
@webfansplz awesome, thanks for the updates!

Looks like that works a lot better now, a few notes on latest:
1. have to alias 'socket.io-client' to 'socket.io-client/dist/socket.io.js' to avoid webpack polyfill errors (this one is simple, so don't think anything needs to change in devtools - just thought I'd mention)
2. disconnects/reconnects work now! 🎉 
3. I still seem to need this in our custom renderer code:
    ```ts
    export const createApp = ((...args) => {
      try {
        if (global.__VUE_DEVTOOLS_GLOBAL_HOOK__) {
          setDevtoolsHook(global.__VUE_DEVTOOLS_GLOBAL_HOOK__ as any, global);
        }
      } catch (err) {
        // ignore
      }
    
     // ...
    ```
4. devtools doesn't seem to update the refs until I re-select the component

https://github.com/vuejs/devtools-next/assets/879060/60a3f6df-e9cd-4f3a-8651-e0eed47de37e

**Comment by webfansplz** [comment]
> @webfansplz awesome, thanks for the updates!
> 
> Looks like that works a lot better now, a few notes on latest:
> 
> 1. have to alias 'socket.io-client' to 'socket.io-client/dist/socket.io.js' to avoid webpack polyfill errors (this one is simple, so don't think anything needs to change in devtools - just thought I'd mention)
> 2. disconnects/reconnects work now! 🎉
> 3. I still seem to need this in our custom renderer code:
>    ```ts
>    export const createApp = ((...args) => {
>      try {
>        if (global.__VUE_DEVTOOLS_GLOBAL_HOOK__) {
>          setDevtoolsHook(global.__VUE_DEVTOOLS_GLOBAL_HOOK__ as any, global);
>        }
>      } catch (err) {
>        // ignore
>      }
>    
>     // ...
>    ```
> 4. devtools doesn't seem to update the refs until I re-select the component
> 
>  Screen.Recording.2024-01-11.at.10.13.35.PM.mov

Hi @rigor789 Thanks for the feedback and glad to see it works now

1. I used `socket.io-client/dist/socket.io.js` at first, but it seems to have some edge case issue, I'll try it again later. 
3. Do you add the `import '@vue/devtools/hook'` before import vue?
4. We'll track it later, thanks.

**Comment by rigor789** [comment]
@webfansplz
Not sure about 1. but I wouldn't worry about it - it works with the alias (and is hidden from the user, so doesn't complicate it for end-users at all)

For 2. I missed that at first, but testing it now with it, and seems like it doesn't change it. But it does look like our bundle is somehow still loading these in the wrong order. I'll try and debug that. I believe it should work once I figure out why the order is incorrect.

**Comment by webfansplz** [comment]
> @webfansplz Not sure about 1. but I wouldn't worry about it - it works with the alias (and is hidden from the user, so doesn't complicate it for end-users at all)
> 
> For 2. I missed that at first, but testing it now with it, and seems like it doesn't change it. But it does look like our bundle is somehow still loading these in the wrong order. I'll try and debug that. I believe it should work once I figure out why the order is incorrect.

Okay, I think it should work when we solve the import order issue. So let's close the issue, and please feel free to reopen the issue if you still have issues after solving the import order issue.

**Comment by rigor789** [comment]
Thanks for your help @webfansplz!
