### ISSUE TITLE
Cannot open standalone app

### ISSUE THREAD

**Issue by BTMuli** [vuejs/devtools-next#146]
在已经全局安装 `@vue/devtools` 的情况下，运行 `vue-devtools` 没有弹出 devtool 窗口

+ `node v21.4.0`
+ `npm v10.2.5`
+ `@vue/devtools v7.0.4`

ps: 尝试运行了一下 `--debug`，竟然有输出，以供参考

```shell
PS > vue-devtools --debug
file:///E:/Code/Environment/Node/node_global/node_modules/@vue/devtools/node_modules/execa/lib/error.js:60
                error = new Error(message);
                        ^

Error: Command failed with exit code 9: E:\Code\Environment\Node\node_global\node_modules\@vue\devtools\node_modules\electron\dist\electron.exe /E:/Code/Environment/Node/node_global/node_modules/@vue/devtools/node_modules/@vue/devtools-electron/dist/app.cjs --debug
    at makeError (file:///E:/Code/Environment/Node/node_global/node_modules/@vue/devtools/node_modules/execa/lib/error.js:60:11)
    at execaSync (file:///E:/Code/Environment/Node/node_global/node_modules/@vue/devtools/node_modules/execa/index.js:201:17)
    at file:///E:/Code/Environment/Node/node_global/node_modules/@vue/devtools/node_modules/@vue/devtools-electron/dist/cli.mjs:6:16
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24) {
  shortMessage: 'Command failed with exit code 9: E:\\Code\\Environment\\Node\\node_global\\node_modules\\@vue\\devtools\\node_modules\\electron\\dist\\electron.exe /E:/Code/Environment/Node/node_global/node_modules/@vue/devtools/node_modules/@vue/devtools-electron/dist/app.cjs --debug',
  command: 'E:\\Code\\Environment\\Node\\node_global\\node_modules\\@vue\\devtools\\node_modules\\electron\\dist\\electron.exe /E:/Code/Environment/Node/node_global/node_modules/@vue/devtools/node_modules/@vue/devtools-electron/dist/app.cjs --debug',
  escapedCommand: '"E:\\Code\\Environment\\Node\\node_global\\node_modules\\@vue\\devtools\\node_modules\\electron\\dist\\electron.exe" "/E:/Code/Environment/Node/node_global/node_modules/@vue/devtools/node_modules/@vue/devtools-electron/dist/app.cjs" --debug',
  exitCode: 9,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  cwd: 'C:\\Users\\19278',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

Node.js v21.4.0
```

**Comment by webfansplz** [comment]
--debug 输出的这个不是打不开的原因。可以帮忙尝试一下局部安装 (`./node_modules/.bin/vue-devtools
 `) 和 更改端口（`PORT=8000 (任意不冲突的端口) vue-devtools`）看看是否可行

**Comment by BTMuli** [comment]
> --debug 输出的这个不是打不开的原因。可以帮忙尝试一下局部安装 (`./node_modules/.bin/vue-devtools `) 和 更改端口（`PORT=8000 (任意不冲突的端口) vue-devtools`）看看是否可行

局部安装情况下：

1. 终端 `vue-devtools` 无响应
2. 调用 `./node_modules/.bin/vue-devtools` 无响应
3. 终端 `PORT=8000 vue-devtools` 显示 `不是内部或外部命令，也不是可运行的程序或批处理文件。`
4. 在 `main.ts` 中使用如下代码（项目运行端口为4444）

    ```typescript
    import { devtools } from "@vue/devtools";

    if (import.meta.env.MODE === "development") {
      console.log("devMode");
      try {
        await devtools.connect("http://localhost", 4444).catch(e => console.error(e));
        console.log("connect");
      } catch (e) {
        console.error(e);
      }
    }
    ```
    终端仅输出 `devMode` `connect`。

**Comment by webfansplz** [comment]
> > --debug 输出的这个不是打不开的原因。可以帮忙尝试一下局部安装 (`./node_modules/.bin/vue-devtools `) 和 更改端口（`PORT=8000 (任意不冲突的端口) vue-devtools`）看看是否可行
> 
> 局部安装情况下：
> 
> 1. 终端 `vue-devtools` 无响应
> 2. 调用 `./node_modules/.bin/vue-devtools` 无响应
> 3. 终端 `PORT=8000 vue-devtools` 显示 `不是内部或外部命令，也不是可运行的程序或批处理文件。`
> 4. 在 `main.ts` 中使用如下代码（项目运行端口为4444）
>    ```ts
>    import { devtools } from "@vue/devtools";
>    
>    if (import.meta.env.MODE === "development") {
>      console.log("devMode");
>      try {
>        await devtools.connect("http://localhost", 4444).catch(e => console.error(e));
>        console.log("connect");
>      } catch (e) {
>        console.error(e);
>      }
>    }
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    终端仅输出 `devMode` `connect`。

MacOS 无法复现问题，看能否提供更多的系统信息。或者看是否有更多人反馈该问题提供更多信息。

**Comment by BTMuli** [comment]
> 看能否提供更多的系统信息

跑了一下 `tauri info`：

```shell
[✔] Environment
    - OS: Windows 10.0.23606 X64
    ✔ WebView2: 120.0.2210.91
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.70.0 (90c541806 2023-05-31)
    ✔ cargo: 1.70.0 (ec8a8a0ca 2023-04-25)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 21.4.0
    - pnpm: 8.14.0
    - npm: 10.2.5

[-] Packages
    - tauri [RUST]: 1.5.4
    - tauri-build [RUST]: 1.5.1
    - wry [RUST]: 0.24.7
    - tao [RUST]: 0.16.5
    - @tauri-apps/api [NPM]: 1.5.3
    - @tauri-apps/cli [NPM]: 1.5.9

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:4000/
    - framework: Vue.js
    - bundler: Vite
```

项目包管理是 `pnpm`

**Comment by alexzhang1030** [comment]
@BTMuli Hey, can you test #153? Thanks!

**Comment by BTMuli** [comment]
> @BTMuli Hey, can you test #153? Thanks!

弹窗报错：`Unable to find Electron app at E:\E:\xxxx`

看上去像是目录路径解析错误？

**Comment by alexzhang1030** [comment]
再看看呢现在，刚修复了这个问题

**Comment by BTMuli** [comment]
> 再看看呢现在，刚修复了这个问题

It works
![image](https://github.com/vuejs/devtools-next/assets/72692909/9a903762-455d-4955-83e4-4931f08c0fde)

**Comment by cesarm-meyersound** [comment]
I'm getting this error. What was the fix?

**Comment by cesarm-meyersound** [comment]
> I'm getting this error. What was the fix?

Removing node options from the environment with `NODE_OPTIONS=` fixed it 🤷
