### ISSUE TITLE
plugin fall into endless loop

### ISSUE THREAD

**Issue by yiludege** [vuejs/devtools-next#159]
1、Current `vite-plugin-vue-devtools` version: 7.0.5

2、Call stack

![132f455b-2b82-4694-824e-0266dbcdb826](https://github.com/vuejs/devtools-next/assets/19788268/5ecb740d-5442-4728-9d60-4551b4c248c2)

3、the route may have circular reference
![image](https://github.com/vuejs/devtools-next/assets/19788268/a4ae545b-ce2a-4579-9a21-0e85e83f6036)

**Comment by webfansplz** [comment]
Can you provide a mini repo or share the routes config? Thank you.

**Comment by sincely** [comment]
<img width="1885" alt="image" src="https://github.com/vuejs/devtools-next/assets/40814642/408c0f13-9fa7-4a21-bfc3-baa5277bac05">
<img width="983" alt="image" src="https://github.com/vuejs/devtools-next/assets/40814642/990f86db-b5f4-4797-b9cb-076f23985286">
I have the same problem again！and there are issues with the development environment!!!!

**Comment by webfansplz** [comment]
> <img alt="image" width="1885" src="https://private-user-images.githubusercontent.com/40814642/295967504-408c0f13-9fa7-4a21-bfc3-baa5277bac05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5ODkxNDUsIm5iZiI6MTcwNDk4ODg0NSwicGF0aCI6Ii80MDgxNDY0Mi8yOTU5Njc1MDQtNDA4YzBmMTMtOWZhNy00YTIxLWJmYzMtYmFhNTI3N2JhYzA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDE2MDA0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwZjY3YTljNDFlNDY0NDVjNjc1ZGIzMDIyOWFjNzZiYjc4NmUwYTk0ZjYxZWUzNjk1YWUyMTdjMDNlOTVhNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oa3E3gKM90MMnP3AwJRk1cJ-Z-izTBTPIIXlSg_RJQ8"> <img alt="image" width="983" src="https://private-user-images.githubusercontent.com/40814642/295967987-990f86db-b5f4-4797-b9cb-076f23985286.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5ODkxNDUsIm5iZiI6MTcwNDk4ODg0NSwicGF0aCI6Ii80MDgxNDY0Mi8yOTU5Njc5ODctOTkwZjg2ZGItYjVmNC00Nzk3LWI5Y2ItMDc2ZjIzOTg1Mjg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDE2MDA0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzODI0YmQzMmY0NmJkNmFlOGQ5YTZlNzcxNjE5NGNmMTFjY2Y3OTA5YmE2OTFiZjQzZWIyY2RjMmE5MGYyZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.V4biBC9t0DJ4QXG5ERsBuyZEo5cS9DHoEnwLPBd4-hw"> I have the same problem again！and there are issues with the development environment!!!!

Can you provide a mini repo or share the routes config? Thank you.

**Comment by webfansplz** [comment]
Fixed in v7.0.10
