### ISSUE TITLE
Delete button does not delete pinia item in the array

### ISSUE THREAD

**Issue by pikax** [vuejs/devtools-next#161]
https://github.com/vuejs/devtools-next/assets/4620458/406b6901-ad80-4850-bb3d-60c6674792b8

Pressing the delete button does not delete the item

**Comment by alexzhang1030** [comment]
Pinia state editor now has some unexpected behaviours😢, we will resolve ASAP.

**Comment by webfansplz** [comment]
Also be related to #109

**Comment by webfansplz** [comment]
> Be related to #109
