### ISSUE TITLE
Can't detect a content script in shadow root for Web Extension app

### ISSUE THREAD

**Issue by neilfranci** [vuejs/devtools-next#169]
**The popup.html works with script tag**

![image](https://github.com/vuejs/devtools-next/assets/66520542/7613f7bb-e89d-46ea-8543-147aad0f8524)

However, the content script is just a JavaScript file built using Vite, I create a script tag and add it to the shadow DOM. Still, the devtool standalone app can't detect it besides looping the icon.

![image](https://github.com/vuejs/devtools-next/assets/66520542/39a14c7d-d035-4249-b364-6564338584b9)

**I'm using the latest version**

- _No, the entry is the JS, not HTML I can't just paste the `<script....`_
- The vue-devtools extension is not detecting it either

**Is there a way to work around this or is my approach wrong?**

**Comment by webfansplz** [comment]
```ts
import devtools from '@vue/devtools'

devtools.connect('http://localhost',8098)
```

You can use the connect function instead. (Notice: please call the connect function before create vue app)

**Comment by neilfranci** [comment]
> ```ts
> import devtools from '@vue/devtools'
> ```

This is what I got 😕
![image](https://github.com/vuejs/devtools-next/assets/66520542/910df458-bdf6-4b81-98a3-39f6ae9c2502)

```
Could not find a declaration file for module '@vue/devtools'. 'D:/Projects/web_extentions/learn-wxt/node_modules/.pnpm/@vue+devtools@7.0.8_vite@5.0.11/node_modules/@vue/devtools/dist/index.mjs' implicitly has an 'any' type.
  There are types at 'd:/Projects/web_extentions/learn-wxt/node_modules/@vue/devtools/dist/index.d.ts', but this result could not be resolved when respecting package.json "exports". The '@vue/devtools' library may need to update its package.json or typings.ts(7016)
```

**Comment by webfansplz** [comment]
> > ```ts
> > import devtools from '@vue/devtools'
> > ```
> 
> This is what I got 😕 ![image](https://private-user-images.githubusercontent.com/66520542/296532977-910df458-bdf6-4b81-98a3-39f6ae9c2502.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyMTkyMDEsIm5iZiI6MTcwNTIxODkwMSwicGF0aCI6Ii82NjUyMDU0Mi8yOTY1MzI5NzctOTEwZGY0NTgtYmRmNi00YjgxLTk4YTMtMzlmNmFlOWMyNTAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE0VDA3NTUwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiZWUyMDhmZmRkNDkyMjViNzc4NDNmZTQ2MDA5ZmRmMDVhZThhMzMwOGY0ZjUxOTE0MzVhZGI3MmUxY2U2ODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pPO_rnPGoGlIeHRmGsYNap1xqWzsJVJ9bu04uU48QN8)
> 
> ```
> Could not find a declaration file for module '@vue/devtools'. 'D:/Projects/web_extentions/learn-wxt/node_modules/.pnpm/@vue+devtools@7.0.8_vite@5.0.11/node_modules/@vue/devtools/dist/index.mjs' implicitly has an 'any' type.
>   There are types at 'd:/Projects/web_extentions/learn-wxt/node_modules/@vue/devtools/dist/index.d.ts', but this result could not be resolved when respecting package.json "exports". The '@vue/devtools' library may need to update its package.json or typings.ts(7016)
> ```

It's just a ts error, you can upgrade to 7.0.10 and try again.

**Comment by webfansplz** [comment]
hi @neilfranci , Is it working properly now?

**Comment by neilfranci** [comment]
> hi @neilfranci , Is it working properly now?

I'm not sure if this working with the normal build-from-scratch web extension using Content Script with shadowRoot. Cuz I'm using a framework for web extension. I can say it show the Component and Pinia but nothing else like Ref..

**Comment by webfansplz** [comment]
> > hi @neilfranci , Is it working properly now?
> 
> I'm not sure if this working with the normal build-from-scratch web extension using Content Script with shadowRoot. Cuz I'm using a framework for web extension. I can say it show the Component and Pinia but nothing else like Ref..

OK, let's close this issue because it can be running now. And we will explore it in the future if more users encounter the same issue.
