### ISSUE TITLE
New Asset Explorer Design Proposal

### ISSUE THREAD

**Issue by YunYouJun** [vuejs/devtools-next#173]
The current assets explorer is a bit of a waste of screen space and needs to switch views.

![image](https://github.com/vuejs/devtools-next/assets/25154432/39818d7a-eeae-4f2e-8f8b-6b438891ec57)
![image](https://github.com/vuejs/devtools-next/assets/25154432/74f93f36-5ee5-4528-9c57-d9dca77d018e)

I made what I thought was a cool asset manager.

https://github.com/vuejs/devtools-next/assets/25154432/de62840f-db8d-4a31-b35b-07e02f2dfa70

What do you think about transforming current resource management into this form?

**Comment by webfansplz** [comment]
Hi @YunYouJun, thanks for the nice sharing, the solution is so cool. But for some reasons, we prefer to keep the current design:

1. For the devtools assets feature, we have some differences with traditional file management (custom preview and action for difference asset type, and extends more features in the future, e.g drag and drop)
2. It would take a lot of work to refactor it
3. We plan to reuse some features with nuxt devtools, so we need to align as much as possible.

**Comment by YunYouJun** [comment]
OK, i got it.

(Of course, it also supports custom actions and drag-and-drop.)
