### ISSUE TITLE
[Feature Request] Graph should be updated in real time

### ISSUE THREAD

**Issue by LoTwT** [vuejs/devtools-next#177]
## description

`Graph` will not update automatically after loading lazy-load routes with vue-router. After switching back to the `Graph` tab, it will update correctly.

https://github.com/vuejs/devtools-next/assets/50254496/fa2ab78b-78f4-4099-ab4e-fc68eb462093

## repro

URL: <https://stackblitz.com/edit/vitejs-vite-nzyucm?file=vite.config.ts>

**Comment by LoTwT** [comment]
Hi, there.

I'm trying to resolve a similar problem in `vite-plugin-inspect` first. I'm not sure if the solution is appropriate. If you are interested in this issue, please check [vite-plugin-inspect #104](https://github.com/antfu/vite-plugin-inspect/pull/104). 😊

**Comment by LoTwT** [comment]
## description

After the [vite-plugin-inspect #104](https://github.com/antfu/vite-plugin-inspect/pull/104) merged, I tried to resolve this issue. I made a demo to test if it can use the RPC function defined in the `vite-plugin-inspect`. The code is as follows

```ts
// client/src/pages/graph.vue
async function foo() {
  const hot = await getViteHotContext()
  if (hot) {
    createRPCClient('vite-plugin-inspect', hot, {
      async moduleUpdated() {
        console.log('module-update')

        try {
          const root = await bridgeRpc.root()
          bridgeRpc.getGraph().then((res) => {
            parseGraphRawData(res, root)
          }).catch(e => console.log('getGraph-error', e))
        }
        catch (error) {
          console.log('update-error', error)
        }
      },
    })
  }
}

onMounted(() => {
  foo()
})
```

The `console.log('module-update')` was triggered successfully. However, when calling the APIs of `bridgeRpc`, it will result in a `timeout` error and the errors are as follows:

<img width="711" alt="image" src="https://github.com/vuejs/devtools-next/assets/50254496/9286ae07-a52e-4b04-9b32-67d89fe36324">

## questions

- The limit of using `bridgeRpc`, if there are some attentions that should be particularly paid to?
- The `moduleUpdated` RPC function is defined in the `vite-plugin-inspect`, but the RPC client available is registered with the name `vite-plugin-vue-devtools` in this repo. I'm not sure using `createRPCClient` directly in the `client` is a more appropriate way. 😢

**Comment by webfansplz** [comment]
> ## description
> After the [vite-plugin-inspect #104](https://github.com/antfu/vite-plugin-inspect/pull/104) merged, I tried to resolve this issue. I made a demo to test if it can use the RPC function defined in the `vite-plugin-inspect`. The code is as follows
> 
> ```ts
> // client/src/pages/graph.vue
> async function foo() {
>   const hot = await getViteHotContext()
>   if (hot) {
>     createRPCClient('vite-plugin-inspect', hot, {
>       async moduleUpdated() {
>         console.log('module-update')
> 
>         try {
>           const root = await bridgeRpc.root()
>           bridgeRpc.getGraph().then((res) => {
>             parseGraphRawData(res, root)
>           }).catch(e => console.log('getGraph-error', e))
>         }
>         catch (error) {
>           console.log('update-error', error)
>         }
>       },
>     })
>   }
> }
> 
> onMounted(() => {
>   foo()
> })
> ```
> 
> The `console.log('module-update')` was triggered successfully. However, when calling the APIs of `bridgeRpc`, it will result in a `timeout` error and the errors are as follows:
> 
> <img alt="image" width="711" src="https://private-user-images.githubusercontent.com/50254496/299209877-9286ae07-a52e-4b04-9b32-67d89fe36324.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwODA0OTEsIm5iZiI6MTcwNjA4MDE5MSwicGF0aCI6Ii81MDI1NDQ5Ni8yOTkyMDk4NzctOTI4NmFlMDctYTUyZS00YjA0LTliMzItNjdkODlmZTM2MzI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDA3MDk1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzNGQ3ZjNiMGU0ODQxYmQ2YjVmZmU5OWFkYTg3ZmQyMTAxNjA4ZWI3ZTUzNjAzNTVlYWQ3ODEwNGZlZDI4M2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tu9jEDZYGTKKgRgoUu9Hj5OURmtqRQzvEIfWA59OufU">
> ## questions
> * The limit of using `bridgeRpc`, if there are some attentions that should be particularly paid to?
> * The `moduleUpdated` RPC function is defined in the `vite-plugin-inspect`, but the RPC client available is registered with the name `vite-plugin-vue-devtools` in this repo. I'm not sure using `createRPCClient` directly in the `client` is a more appropriate way. 😢

Try to add `timeout: -1` to the `vite-dev-rpc` option

**Comment by webfansplz** [comment]
> > ## description
> > After the [vite-plugin-inspect #104](https://github.com/antfu/vite-plugin-inspect/pull/104) merged, I tried to resolve this issue. I made a demo to test if it can use the RPC function defined in the `vite-plugin-inspect`. The code is as follows
> > ```ts
> > // client/src/pages/graph.vue
> > async function foo() {
> >   const hot = await getViteHotContext()
> >   if (hot) {
> >     createRPCClient('vite-plugin-inspect', hot, {
> >       async moduleUpdated() {
> >         console.log('module-update')
> > 
> >         try {
> >           const root = await bridgeRpc.root()
> >           bridgeRpc.getGraph().then((res) => {
> >             parseGraphRawData(res, root)
> >           }).catch(e => console.log('getGraph-error', e))
> >         }
> >         catch (error) {
> >           console.log('update-error', error)
> >         }
> >       },
> >     })
> >   }
> > }
> > 
> > onMounted(() => {
> >   foo()
> > })
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The `console.log('module-update')` was triggered successfully. However, when calling the APIs of `bridgeRpc`, it will result in a `timeout` error and the errors are as follows:
> > <img alt="image" width="711" src="https://private-user-images.githubusercontent.com/50254496/299209877-9286ae07-a52e-4b04-9b32-67d89fe36324.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwODA0OTEsIm5iZiI6MTcwNjA4MDE5MSwicGF0aCI6Ii81MDI1NDQ5Ni8yOTkyMDk4NzctOTI4NmFlMDctYTUyZS00YjA0LTliMzItNjdkODlmZTM2MzI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDA3MDk1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzNGQ3ZjNiMGU0ODQxYmQ2YjVmZmU5OWFkYTg3ZmQyMTAxNjA4ZWI3ZTUzNjAzNTVlYWQ3ODEwNGZlZDI4M2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tu9jEDZYGTKKgRgoUu9Hj5OURmtqRQzvEIfWA59OufU">
> > ## questions
> > * The limit of using `bridgeRpc`, if there are some attentions that should be particularly paid to?
> > * The `moduleUpdated` RPC function is defined in the `vite-plugin-inspect`, but the RPC client available is registered with the name `vite-plugin-vue-devtools` in this repo. I'm not sure using `createRPCClient` directly in the `client` is a more appropriate way. 😢
> 
> Try to add `timeout: -1` to the `vite-dev-rpc` option

**Comment by LoTwT** [comment]
@webfansplz `timeout:-1` doesn't work. Before, I tried the original communication way of vite using `server.ws.send` and `import.meta.hot.on`, but the `bridgeRpc` still doesn't work yet. 😢
