### ISSUE TITLE
Hangs navigating large arrays/objects

### ISSUE THREAD

**Issue by richardtallent-erm** [vuejs/devtools-next#179]
My page has several arrays, sets, maps, objects, etc. that have thousands or tens of thousands of members.

The fix mentioned in #132 resolves the problem of the initial load, but when I try to navigate a component's state in the tools and I expand one of these objects, it takes sometimes *minutes* to open the list, as it is rendering a row for every item in that object.

IIRC, the old browser extension would detect objects with many members and would only show a portion (100?) of the results, followed by a clickable "..." to open more. The web version did something similar.

**Comment by webfansplz** [comment]
If anyone is interested in supporting it, we can do it here: https://github.com/vuejs/devtools-next/blob/main/packages/client/src/components/inspector/InspectorStateField.vue#L55

In addition, we also need support objects, maps, sets, etc.
