### ISSUE TITLE
[bug] fail to open assets in editor on macOS

### ISSUE THREAD

**Issue by LoTwT** [vuejs/devtools-next#185]
## description

fail to open assets in editor on macOS

https://github.com/vuejs/devtools-next/assets/50254496/ce3763c8-1d24-469a-ba98-d0eaf70ab975

## version

"vite-plugin-vue-devtools": "^7.0.11",

## env info

 - System:
    - OS: macOS 14.3
    - CPU: (10) arm64 Apple M1 Pro
    - Memory: 3.53 GB / 32.00 GB
    - Shell: 5.9 - /bin/zsh
- Binaries:
    - Node: 20.11.0 - ~/Library/Caches/fnm_multishells/64820_1705656024800/bin/node
    - npm: 10.2.4 - ~/Library/Caches/fnm_multishells/64820_1705656024800/bin/npm
    - pnpm: 8.14.1 - ~/Library/pnpm/pnpm
- Browsers:
    - Chrome: 120.0.6099.234
- npmPackages:
    - vue: ^3.4.15 => 3.4.15 

## additional context

It works in the stackblitz.

URL: <https://stackblitz.com/edit/vitejs-vite-b2m26r?file=vite.config.ts>

**Comment by webfansplz** [comment]
> /cc @webfansplz Does `package.json` should be here？

Yeah, I think it makes sense to show it.

**Comment by titibudala** [comment]
Same configuration (mostly) and same issue as @LoTwT 

![Alt Text](https://media.giphy.com/media/f3dRSiajsz8DLmt0KS/giphy-downsized.gif)

**Comment by alexzhang1030** [comment]
@LoTwT Can you show your `real` file path and the incorrect file path of the assets page? You can hover the `file path` row to get the details.

**Comment by LoTwT** [comment]
> @LoTwT Can you show your `real` file path and the incorrect file path of the assets page? You can hover the `file path` row to get the details.

The filepath on the assets page:

<img width="491" alt="image" src="https://github.com/vuejs/devtools-next/assets/50254496/e1dcaa37-24d1-43bf-8299-9655d6b8c0d0">

The filepath copied in VSCode: `/Users/caoyujie/codes/vite-assets/package.json`.

They are the same indeed.

**Comment by alexzhang1030** [comment]
Unfortunately, I can't reproduce this issue, so we need your help to test it. The capabilities of our openInEditor feature are supported by Vite [built-in](https://github.com/vitejs/vite/blob/main/packages/vite/src/node/server/index.ts#L788).

Can you test this Vite feature? That will help us to find out if this is an upstream issue. Thank you.

**Comment by LoTwT** [comment]
> Unfortunately, I can't reproduce this issue, so we need your help to test it. The capabilities of our openInEditor feature are supported by Vite [built-in](https://github.com/vitejs/vite/blob/main/packages/vite/src/node/server/index.ts#L788).
> 
> Can you test this Vite feature? That will help us to find out if this is an upstream issue. Thank you.

Thanks.

I tried the URL `http://localhost:5173/__open-in-editor?file=package.json` manually. It comes into the same error. I will try to find the problem myself locally.

**Comment by alexzhang1030** [comment]
> > Unfortunately, I can't reproduce this issue, so we need your help to test it. The capabilities of our openInEditor feature are supported by Vite [built-in](https://github.com/vitejs/vite/blob/main/packages/vite/src/node/server/index.ts?rgh-link-date=2024-01-23T03%3A53%3A19Z#L788).
> > Can you test this Vite feature? That will help us to find out if this is an upstream issue. Thank you.
> 
> Thanks.
> 
> I tried the URL `http://localhost:5173/__open-in-editor?file=package.json` manually. It comes into the same error. I will try to find the problem myself locally.

No... the query `file` should be your `absolute file path`, try it out

**Comment by LoTwT** [comment]
After looking around the codebase of `launch-editor-middleware`, I find that the command to open VSCode on macOS is [`code`](https://github.com/yyx990803/launch-editor/blob/5ad87f680410710e261f4acdaddecaa808312029/packages/launch-editor/editor-info/osx.js#L14). It means that developers must install the command `code` in `PATH`. Unfortunately, I didn't set it well.

How to set:

- open a VSCode
- use `Shift + Command + P` open All Commands panel
- input `Shell Command: Install 'code' command in PATH` and select
- install successfully

After setting it, I successfully open the target file in the VSCode.

Hi, @titibudala . Could you try the above solution? 😊

**Comment by webfansplz** [comment]
I'll mention it in the document, also be related to #125

**Comment by titibudala** [comment]
Yesss! That was it @LoTwT, thank you! 🫡
