### ISSUE TITLE
Why do I need a delayed mount to use the vite plugin

### ISSUE THREAD

**Issue by meitan-li** [vuejs/devtools-next#191]
I have a new project.
![image](https://github.com/vuejs/devtools-next/assets/141155927/cb95b9f6-44e8-488e-83a7-b47920f57b70)
![image](https://github.com/vuejs/devtools-next/assets/141155927/a50893a9-3eaf-46c2-8db9-7c193e379f0f)
![image](https://github.com/vuejs/devtools-next/assets/141155927/c697a207-ca21-44d2-b979-ca96aa48b987)
![image](https://github.com/vuejs/devtools-next/assets/141155927/04860840-c909-44f7-8a18-c78506d2c57a)

When starting the project, I can't use the plugin.
And click on the "Inspector" button, I will get the error:
![image](https://github.com/vuejs/devtools-next/assets/141155927/43400c87-9a4c-4164-a315-66c2fcd5c775)

I found that if I mount in "setTimeout", everything will be fine:
![image](https://github.com/vuejs/devtools-next/assets/141155927/70e79d9f-579d-4b67-bed8-a4784919242b)
![image](https://github.com/vuejs/devtools-next/assets/141155927/05451cd0-3cc5-4ac0-be65-f60d65010e11)

🙏

**Comment by alexzhang1030** [comment]
Can you share a minimal reproduction? Thank you!

**Comment by meitan-li** [comment]
> Can you share a minimal reproduction? Thank you!

I created a project, please check it.
https://github.com/meitan-li/vue-devtool-next-demo
You can modify the code in `src/main.ts` to reproduce the issue.

Thank you!!
