### ISSUE TITLE
[feature request] update reactively and add a refresh button for assets

### ISSUE THREAD

**Issue by LoTwT** [vuejs/devtools-next#200]
## description

After creating new asset files in the project, the assets tab will not update reactively and has no refresh button now. Adding a refresh button and updating assets reactively will increase DX.

## expected

- add a refresh button
- update assets' states reactively

## to confirm

- how to watch the creation and deletion of assets ( need to find an appropriate way )
- should the states of assets in the preview drawer be updated reactively? ( It could rely on vite hmr )

**Comment by OneGIl** [comment]
不知道是否可以参考老版的 vite-plugin-vue-devtools 中的代码？ 我曾提交过一个pr，里面包含了file watch的功能。
希望对你有帮助: ) [vite-plugin-vue-devtools #183](https://github.com/webfansplz/vite-plugin-vue-devtools/pull/183)
