### ISSUE TITLE
Should the root of scanning assets be strongly related to `root` in the `vite.config.ts`？

### ISSUE THREAD

**Issue by LoTwT** [vuejs/devtools-next#201]
## description

The scanning of assets is now based on the `root` in the `vite.config.ts`. After setting the root to some other path instead of `process.cwd()`, files such as `package.json`, `README.md`, and so on will not display in the assets tab. I think this behavior is a litter strange. We could find a better way to display "all" the asset files in a more natural way.

## repro

URL: <https://stackblitz.com/edit/vitejs-vite-j2b3x7?file=vite.config.ts>

**Comment by LoTwT** [comment]
Hi, @webfansplz.

What do you think the behaviors should be? Should "all" the asset files be included and scanned?

**Comment by webfansplz** [comment]
> Hi, @webfansplz.
> 
> What do you think the behaviors should be? Should "all" the asset files be included and scanned?

Yep. I think scanning all of the asset files makes sense.

**Comment by alexzhang1030** [comment]
In my opinion, [root](https://vitejs.dev/guide/#specifying-alternative-root) is an entrance of a vite app (or vue app), what people care about **what they have** or **what they use**, not **what they put in codebase**. Scanning non-root asset files is nonsense because we cannot use them in our project.

**Comment by LoTwT** [comment]
I think it's a question more about product design than tech. 

Project structures vary depending on developers. When I was creating this issue, I thought that the project structure mainly relied on the `front-end` repo. So it sometimes requires writing docs based on pages. But making the assets list clean and has less noise is also important.🤣

**Comment by LoTwT** [comment]
This is not an explicit issue. I think it should be closed now.
