### ISSUE TITLE
Question: how to add custom tab in vite-plugin-vue-devtools?

### ISSUE THREAD

**Issue by Clarkkkk** [vuejs/devtools-next#229]
I saw that there is an api [addCustomTab](https://devtools-next.vuejs.org/plugins/api#addcustomtab) to add new tabs in devtools. Can i use it in `vite-plugin-vue-devtools`?

**Comment by webfansplz** [comment]
> Do you mean https://devtools-next.vuejs.org/guide/vite-plugin? I don't see the relevant options there 😂. Can you provide an example?

https://github.com/vuejs/devtools-next/blob/main/packages/playground/src/main.ts#L58
