### ISSUE TITLE
The DevTools's color scheme will conflict with the color scheme of the project itself

### ISSUE THREAD

**Issue by hooray** [vuejs/devtools-next#233]
I see that DevTools adds `light/dark` class name to the HTML tag when switching color scheme, but there are some UI component libraries that also do color scheme switching via `light/dark` on the HTML tag, which results in switching color schemes in devtools and the current project's color scheme being affected.

I think DevTools should be given a different class name, such as `devtools-light/devtools-dark`

https://github.com/vuejs/devtools-next/assets/1574903/d70de92e-832f-4e2a-9b8c-7183822ef845

**Comment by webfansplz** [comment]
That's by design. We prefer that the theme be as consistent as possible, follow the system, and be as consistent as possible with the user application environment.

**Comment by javatong** [comment]
I was messed up because I always thought there was a problem with my @vue/use. After following all the code, I found that it still automatically follows the system to change the dark mode. Finally, I had no choice but to build a new project and found that removing vite-plugin-vue-devtools plugin would not automatically change it

**Comment by webfansplz** [comment]
Also be related to https://github.com/vuejs/devtools-next/discussions/111#discussioncomment-9108247

**Comment by webfansplz** [comment]
I agree that we should isolate and avoid app conflicts with users as much as possible.

**Comment by javatong** [comment]
Thank you for your reply. Looking forward to the new version

**Comment by javatong** [comment]
> Hi, there.
> 
> What about adding some options to control whether the themes between the user project and the overlay injected by the Vite plugin should be the same?
> 
> I prefer the themes to be the same wherever I change them, while some projects don't use `Vueuse` or the developers expect them to be isolated. Could it be an enhancement?

Good idea, I think so too
