### ISSUE TITLE
[bug] @vue_devtools-api.js does not provide an export named 'setupDevtoolsPlugin' (when using 'addCustomTab')

### ISSUE THREAD

**Issue by jbmaisner** [vuejs/devtools-next#236]
Hi there,

I'm looking to develop a plugin for the new devtool, and I'm encountering a problem.
When I want to use the `addCustomTab` method imported from **@vue/devtools-api**, I encounter the error mentioned in the title (see screenshot below).

![CleanShot 2024-02-09 at 18 19 14@2x](https://github.com/vuejs/devtools-next/assets/5312996/2747a9f0-09c2-49d2-b3fe-21af029730c6)

Here is my code:

```ts
// in main.ts

import { setupDevtools } from 'devtool/vue-devtools';

const sandboxApp = createApp(App)
  .use(router)
  .mount('#app');

setupDevtools();
```

```ts
// in devtool/vue-devtools.ts

import { addCustomTab } from '@vue/devtools-api';

export function setupDevtools () {
  // a simple console.log of the method is enough to trigger the error
  console.log(addCustomTab);

  console.log('Orion Devtools initialized');
}
```

If I comment out the `console.log`, I don't get any errors until I uncomment it.

What's strange is that once the error appears, I have to do a complete clean of the **node_modules** folder for it to work again by commenting out the `console.log`.

My environment:

```bash
MacOS 14.3.1

node -v
# v20.11.0

npm -v
# 10.2.4
```

Here are my devDependencies:

```json
"devDependencies": {
  "@babel/plugin-proposal-decorators": "^7.23.9",
  "@babel/preset-typescript": "^7.23.3",
  "@faker-js/faker": "^8.4.0",
  "@stackblitz/sdk": "^1.9.0",
  "@types/cleave.js": "^1.4.12",
  "@types/cli-progress": "^3.11.5",
  "@types/fs-extra": "^11.0.4",
  "@types/lodash-es": "^4.17.12",
  "@types/node": "^20.11.16",
  "@types/pluralize": "^0.0.33",
  "@types/prismjs": "^1.26.3",
  "@types/voca": "^1.4.5",
  "@typescript-eslint/eslint-plugin": "^6.21.0",
  "@typescript-eslint/parser": "^6.21.0",
  "@vitejs/plugin-vue": "^5.0.3",
  "@vitejs/plugin-vue-jsx": "^3.1.0",
  "@vue/compiler-sfc": "^3.4.16",
  "@vue/devtools-api": "^7.0.14",
  "@vue/eslint-config-prettier": "^9.0.0",
  "@vue/eslint-config-typescript": "^12.0.0",
  "@vuepress/bundler-vite": "^2.0.0-rc.7",
  "@vuepress/plugin-docsearch": "^2.0.0-rc.3",
  "@vuepress/plugin-register-components": "^2.0.0-rc.3",
  "@vuepress/theme-default": "^2.0.0-rc.14",
  "eslint": "^8.56.0",
  "eslint-plugin-vue": "^9.21.1",
  "fs-extra": "^11.2.0",
  "less": "^4.2.0",
  "markdown-it": "^14.0.0",
  "markdown-it-container": "^4.0.0",
  "prismjs": "^1.29.0",
  "ts-morph": "^21.0.1",
  "typescript": "^5.3.3",
  "vite": "^5.1.0",
  "vite-plugin-babel": "^1.2.0",
  "vite-plugin-vue-devtools": "^7.0.14",
  "vue": "^3.4.16",
  "vue-router": "^4.2.5",
  "vue-tsc": "^1.8.27",
  "vue3-markdown-it": "^1.0.10",
  "vuepress": "^2.0.0-rc.7",
  "vuepress-vite": "^2.0.0-rc.0"
}
```

Let me know if you need further informations.

Thanks for your help.

**Comment by webfansplz** [comment]
Can you provide a mini repo? thanks.

**Comment by jbmaisner** [comment]
> Can you provide a mini repo? thanks.

of course, here it is:
[https://github.com/orion-ui/orion-ui/tree/feature/devtool](https://github.com/orion-ui/orion-ui/tree/feature/devtool)

On the `feature/devtool` branch

Simply clone the repo, `npm i` and `npm run serve`.

You will immediatly see the error.

**Comment by webfansplz** [comment]
> > Can you provide a mini repo? thanks.
> 
> of course, here it is: https://github.com/orion-ui/orion-ui/tree/feature/devtool
> 
> On the `feature/devtool` branch
> 
> Simply clone the repo, `npm i` and `npm run serve`.
> 
> You will immediatly see the error.

Hi @jbmaisner , I've submitted a [pr](https://github.com/orion-ui/orion-ui/pull/17) in `orion-ui` to make it work.  The reason for this issue is that `devtools-api` v6 has some compatibility issues with v7. (I'll discuss it with the team later and decide what to do with it). Now, as a workaround, it works fine.

**Comment by Akryum** [comment]
Maybe we should put a tag `next` to the npm releases to prevent conflicts with the current devtools @webfansplz
