### ISSUE TITLE
Cannot able to use `vite-dev-tools` in laravel project.

### ISSUE THREAD

**Issue by alokVishu** [vuejs/devtools-next#251]
Hello,

I am trying to use the `vite-plugin-vue-devtools` in a Vuejs + Laravel-based project but I cannot use it because Laravel serves the template in 8000 port by `php artisan serve` command and vite run on `5173`

How to resolve it?

**Comment by chiehw** [comment]
Is there any output from vite? devtool-next will be injected by vite

**Comment by alokVishu** [comment]
@chiehw, there is no output from Vite. If you open `http://localhost:5173/__devtools__/`, you will only see the message "Waiting for connection..."

**Comment by alokVishu** [comment]
Hello @webfansplz,

I have tried this, but it doesn't seem to work for me.

**Comment by rugaard** [comment]
@webfansplz I experience the same issue as @alokVishu. When using the `appendTo` it does indeed append imports the the file, but while trying to load those imports in the browser, it results in some funky virtual URL (`@id` something) which returns as 404 🤷‍♂️

**Comment by scottbrodersen** [comment]
My situation is similar but my Vue app that is served by a Go app. The Vue app makes calls to the Go backend as well. I got things working by running the Vue app using vite (port `5173`) and configuring a proxy to route backend calls to the Go server (port `3000`). 

My server config in `vite.config.js`:

```javascript
    config.server = {
      hmr: {
        host: 'localhost',
        overlay: true,
      },
      proxy: {
        '/api': {
          target: 'http://localhost:3000',
          secure: false,
          },
        },
      },
    };
```

**Comment by Smef** [comment]
This is available now, and appears to work well. The only config you need is:
```js
        plugins: [
            VueDevTools({
                appendTo: "app.ts",
            }),
            ...
            ...
         ],
```

It seems the separate window option at `https://my-host.test:5173/__devtools__/` isn't yet functional, but this is still significantly better.

**Comment by lighth7015** [comment]
Not working for me, I have an example of this not working on [stackblitz](https://stackblitz.com/edit/github-u322fz).

**Comment by b-maslennikov** [comment]
I have the same problem using `netlify dev`
`{ appendTo: './src/app.ts' }` does not work.
