### ISSUE TITLE
Vue Dev Tools does not display if using Nuxt 3 and cannot install Vue 3 with Nuxt 3 as there is a conflict

### ISSUE THREAD

**Issue by 413D3Z** [vuejs/devtools-next#252]

**Comment by webfansplz** [comment]
For Nuxt devs, We recommend using [nuxt-devtools](https://github.com/nuxt/devtools) for a more powerful developer experience. We'll integrate `Pinia` and `Components` features into the Nuxt DevTools in the future.

**Comment by yuemeng200** [comment]
> For Nuxt devs, We recommend using [nuxt-devtools](https://github.com/nuxt/devtools) for a more powerful developer experience. We'll integrate `Pinia` and `Components` features into the Nuxt DevTools in the future.

But Nuxt DevTools can't show components tree and state such as ref and props

**Comment by webfansplz** [comment]
> > For Nuxt devs, We recommend using [nuxt-devtools](https://github.com/nuxt/devtools) for a more powerful developer experience. We'll integrate `Pinia` and `Components` features into the Nuxt DevTools in the future.
> 
> But Nuxt DevTools can't show components tree and state such as ref and props

This feature is also in the works and we will be integrating it into nuxt devtools.

**Comment by Smef** [comment]
Hopefully this will be built in soon, as it's extremely, extremely helpful.

In the mean time, you can use Vue DevTools Next in [stand-alone mode](https://devtools-next.vuejs.org/guide/standalone) by adding the script to your head of your Nuxt app.

**Comment by webfansplz** [comment]
Close it for now. Vue DevTools already have support to run it in Nuxt. and Nuxt already integrated components-tree and Pinia panel.
