### ISSUE TITLE
If the standalone app can be triggered from the overlay?

### ISSUE THREAD

**Issue by LoTwT** [vuejs/devtools-next#271]
## description

I tried to use the `devtools-next` in a project powered by tauri v2 and vue3. The simulator's width isn't wide.

 If the standalone app can be triggered from the overlay?  If it can be implemented, it's helpful for better DX.

<img width="402" alt="image" src="https://github.com/vuejs/devtools-next/assets/50254496/19cfe47a-e7cc-4d23-b759-b5c344e7672d">

**Comment by alexzhang1030** [comment]
You may want to open a separate window.
<img width="1075" alt="image" src="https://github.com/vuejs/devtools-next/assets/49969959/30f7686c-e9d3-43b5-9232-0e914ab88ccf">

Standalone cannot access features that vite powered, so these two cannot combined.

**Comment by LoTwT** [comment]
> You may want to open a separate window. <img alt="image" width="1075" src="https://private-user-images.githubusercontent.com/49969959/311934591-30f7686c-e9d3-43b5-9232-0e914ab88ccf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyMjMwNDQsIm5iZiI6MTcxMDIyMjc0NCwicGF0aCI6Ii80OTk2OTk1OS8zMTE5MzQ1OTEtMzBmNzY4NmMtZTlkMy00M2I1LTkyMzItMGU5MTRhYjg4Y2NmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDA1NTIyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyYzEyOTJlMjA5M2ZkYjUyMjUwNzc0MGNlNGViNWY1N2RkYWIwMTVjZDQ1ZGU2ZGM2NmE3ODE0Zjg0ZDIzMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TrxaiqQPaY-4pkDfP2iYYP16qkMgKNK_PsYA0dKGvBI">
> 
> Standalone cannot access features that vite powered, so these two cannot combined.

In my case, the separate window is always `waiting for connection`. It might be a bug.

**Comment by alexzhang1030** [comment]
That's because the separate window features use `WindowsChannel` for message communication.
The only way is to open the user app and separate window dev tools in the same browser.

**Comment by LoTwT** [comment]
Could the separate window be designed to be compatible with cross-end apps powered by Electron and Tauri compatibly? Or developers should only explicitly use the standalone app?

**Comment by linkurzweg** [comment]
@LoTwT Can you tell me how to use the devtools as an overlay in Tauri? When I run them in a separate window, it doesn't work most of the time...
