### ISSUE TITLE
DevTools is not displayed in uniapp h5

### ISSUE THREAD

**Issue by Ares-Chang** [vuejs/devtools-next#272]
Hello, I introduced this plugin in uniapp h5, I used the 'vite-plugin-vue-devtools@0.5.1' version before, everything is fine.

The DevTools panel does not appear on the page after the updated version

I found its panel element and manually displayed it to make sure it was properly inserted into the page.
 
![image](https://github.com/vuejs/devtools-next/assets/36911513/67d95be3-0cfa-4052-964c-0d8ec0872d2f)

You can visit the repository [uni-vitesse](https://github.com/Ares-Chang/uni-vitesse), download and install the dependency, and run `pnpm dev:h5` to see the effect

 Thanks!

**Comment by webfansplz** [comment]
I cloned the uni-vitesse repo and run `dev:h5` script, it seems work fine.

**Comment by hilonliao** [comment]
I also encountered the same problem

**Comment by alexzhang1030** [comment]
Which version are you using?

**Comment by Ares-Chang** [comment]
I'm so sorry to interrupt.

I fixed the problem, it may be caused by a browser plugin conflict.

I installed Dark Reader and set the shortcut 'Alt + Shirt + D'

It conflicts with the project's shortcut key, and I don't know why it doesn't display, but it works fine in the incognito window browser.

Thanks a lot

**Comment by Ares-Chang** [comment]
> I also encountered the same problem。
> 
> **environment information:** node: 20.10.0 pnpm: 8.14.1 vite: 5.0.10 vite-plugin-vue-devtools: 7.0.16

You can refer to whether there is any conflict caused.

I don't think it's a problem to insert content directly into the body, maybe there's a data conflict somewhere.

hope this helps
