### ISSUE TITLE
Uncaught SyntaxError: Unterminated string in JSON at position 10024

### ISSUE THREAD

**Issue by nekorrrr** [vuejs/devtools-next#274]
I get the same error message as in the title

![image](https://github.com/vuejs/devtools-next/assets/45645775/7b1e28d2-29b1-4c40-8329-e9e2f9b3d515)

This error occurs when I focus on the input box of a deeper component

This is what I got after debugging it
![image](https://github.com/vuejs/devtools-next/assets/45645775/d424895a-b628-4b6b-9b87-72815c50049b)

I realized that the string in this t variable is not a legal json string
There are some strings that seem to be omitted
![image](https://github.com/vuejs/devtools-next/assets/45645775/221c1291-81e7-4733-bad8-189711c0f04d)

Can you give me some tips?
Thanks

---------------
OS: windows 11
Node: v20.10.0
npm: 10.2.3
pnpm:8.15.4
devtools:@last
naiveUI:@last
---------------

**Comment by major697** [comment]
Same error, like here: https://github.com/vuejs/devtools-next/issues/273

**Comment by webfansplz** [comment]
Can you provide a mini repo? thanks 🙏

**Comment by nekorrrr** [comment]
> Can you provide a mini repo? thanks 🙏

https://github.com/nekorrrr/vue-devtools-issue-274

step1: pnpm install
step2: pnpm run dev
step3: access to「http://localhost:3333/hi/other」
step4: 
![image](https://github.com/vuejs/devtools-next/assets/45645775/15c55aea-5d9d-49cd-8959-2a24096cfbf6)
step5:
![image](https://github.com/vuejs/devtools-next/assets/45645775/e63a78dc-fff9-45a6-8528-2a0554695e6b)
step6: open Developer console
step7:
![image](https://github.com/vuejs/devtools-next/assets/45645775/148f6621-5282-490c-9b17-59929af72e61)
step8:
![image](https://github.com/vuejs/devtools-next/assets/45645775/7f595997-8121-47eb-ada2-f6eb1fdc3a0a)

**Comment by webfansplz** [comment]
Fixed in v7.0.17
