### ISSUE TITLE
devtools is not displayed

### ISSUE THREAD

**Issue by hilonliao** [vuejs/devtools-next#276]
<img width="1003" alt="image" src="https://github.com/vuejs/devtools-next/assets/5449597/e421b24a-c902-4359-846f-c9042c902167">

environment information:
node: 20.10.0
pnpm: 8.14.1
vite: 5.0.10
vite-plugin-vue-devtools: 7.0.16

**Comment by webfansplz** [comment]
Can you provide a mini repo? thanks 🙏
