### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'root')

### ISSUE THREAD

**Issue by luoriwusheng-xia** [vuejs/devtools-next#310]
![image](https://github.com/vuejs/devtools-next/assets/152823466/646279ec-d31b-41f0-9025-bdbcaea5cceb)

```js
(索引):71 
 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'root')
    at fh ((索引):71:9462)
    at FP ((索引):71:22434)
    at (索引):71:23322
    at (索引):71:38927
    at Array.forEach (<anonymous>)
    at (索引):71:38916
    at Kh.callHookWith ((索引):71:3604)
    at ka.getInspectorState ((索引):71:38897)
    at ka.sendInspectorState ((索引):71:39438)
    at (索引):71:23705
```

```
node: 20.10.0

vue-devtools@ 7.0.25

edge @123.0.2420.65 (正式版本) (64 位)
```

- use `pnpm install  packages`
- use global  cli    `vue-devtools`  7.0.25

```json
 "dependencies": {
    "axios": "^1.6.8",
    "nprogress": "^0.2.0",
    "vant": "^4.8.8",
    "vue": "^3.4.21",
    "vue-router": "^4.3.0"
  },
  "devDependencies": {
    "@vant/auto-import-resolver": "^1.1.0",
    "@vitejs/plugin-vue": "^5.0.4",
    "postcss-px-to-viewport-8-plugin": "^1.2.3",
    "sass": "^1.72.0",
    "unplugin-auto-import": "^0.17.5",
    "unplugin-vue-components": "^0.26.0",
    "vite": "^5.2.7",
    "vite-plugin-vue-devtools": "^7.0.25"
  }
```

[en]: I didn't do anything very complicated, I just entered a few words in the input box and the console reported an error.
[zh-cn]: 我没有做很复杂的事情，就是在input框内输入了几个文字，然后控制台就报错了。

[en]: As of April 3, 2024, all dependencies are the latest version

[zh-cn]: 截止到2024-04-03 所有的依赖均为最新版本

**Comment by webfansplz** [comment]
可以帮忙提供一个最小可复现吗 🙏

**Comment by luoriwusheng-xia** [comment]
`vite-plugin-vue-devtools `   I just installed the dependency, but I didn't use this plugin in Vite（vite.config.js） later on

**Comment by luoriwusheng-xia** [comment]
> 可以帮忙提供一个最小可复现吗 🙏

稍等， 我晚点上传一下。  谢谢。

**Comment by TheNovemberRain** [comment]
same problem

`@vue/devtools: 7.0.15`
`vue: 3.4.8`

**Comment by luoriwusheng-xia** [comment]
> 可以帮忙提供一个最小可复现吗 🙏

不知道为何，在项目中能复现， 把逻辑代码都去掉，单独新建仓库， 就无法复现。

主要是在 一个 input 框内 疯狂输入，然后再业务里面才出现的。

**Comment by webfansplz** [comment]
> same problem
> 
> `@vue/devtools: 7.0.15` `vue: 3.4.8`

Can you help to provide a mini repo? thanks 🙏

**Comment by webfansplz** [comment]
Try to upgrade to v7.0.26 and please feel free to reopen it if still meeting the issue.
