### ISSUE TITLE
多个 App 实例的时候，点击 component 的时候报错

### ISSUE THREAD

**Issue by theniceangel** [vuejs/devtools-next#324]
如果页面存在多个 App 实例，第一次打开插件的 component 视图，会报如下的错误：

<img width="1366" alt="image" src="https://github.com/vuejs/devtools-next/assets/25956811/e60150a0-9bf4-4c64-8f4a-5b2dd515d987">

复现的代码也很简单，如下：

<img width="491" alt="image" src="https://github.com/vuejs/devtools-next/assets/25956811/a7fceb97-920d-4cde-8c1e-84f8cd57f6e5">

[vue-devtools-demo.zip](https://github.com/vuejs/devtools-next/files/14916421/vue-devtools-demo.zip)

**Comment by theniceangel** [comment]
用的版本号是："vite-plugin-vue-devtools": "^7.0.25"

**Comment by webfansplz** [comment]
7.0.26 已修复

**Comment by theniceangel** [comment]
> 7.0.26 已修复

虽然没报错了，但是这个时候不应该显示两个 App 程序吗？
<img width="1694" alt="image" src="https://github.com/vuejs/devtools-next/assets/25956811/ebef7809-ef6d-47f2-ac1b-9d620a703b5e">
然后我对比了一下 Chrome 的 Vue 插件，可以识别两个 App。
<img width="1716" alt="image" src="https://github.com/vuejs/devtools-next/assets/25956811/c551e704-e6f0-4160-a269-c4ac57a859fc">

**Comment by theniceangel** [comment]
一个 html 上可能存在多个 App，不管是同步还是异步创建的，应该要考虑这个 case。
