### ISSUE TITLE
Open component in editor opens others editor instead of VSCode

### ISSUE THREAD

**Issue by liuliyehuo** [vuejs/devtools-next#341]
目前情况是我会同时打开idea/webstorm和vscode，当我点击inspector选中元素时，文件会在idea/webstorm中打开文件，而不是vscode，我查了一下配置文档，好像没有找到相关的配置可以进行设置

**Comment by liuliyehuo** [comment]
vite-plugin-vue-devtools的版本号为7.0.27

**Comment by alexzhang1030** [comment]
看 [这个](https://github.com/yyx990803/launch-editor#custom-editor-support). 默认不行的话需要手动设置一下环境变量

**Comment by alexzhang1030** [comment]
See: https://devtools-next.vuejs.org/guide/faq#i-can-t-use-the-open-in-editor-feature

**Comment by Kento97** [comment]
> See: https://devtools-next.vuejs.org/guide/faq#i-can-t-use-the-open-in-editor-feature

PAGE NOT FOUND

**Comment by HeiShuXianSheng** [comment]
> https://devtools-next.vuejs.org/help/faq#i-can-t-use-the-open-in-editor-feature

@alexzhang1030 ，多人协作的项目，有人是用vscode，有人是用webstorm。目前在我电脑上的行为是默认打开了vscode，修改launchEditor可以改为webstorm打开。但是如何检测当前打开的编辑器，然后让其打开文件以适配多人协作？
