### ISSUE TITLE
How to catch component's event?

### ISSUE THREAD

**Issue by hezhongfeng** [vuejs/devtools-next#344]
Timeline just have piana or router's event.

<img width="566" alt="image" src="https://github.com/vuejs/devtools-next/assets/12163050/4311e504-fc13-48d5-a135-17c5f11d938d">

**Comment by webfansplz** [comment]
See https://github.com/vuejs/devtools-next/discussions/111#discussioncomment-8092703

**Comment by hezhongfeng** [comment]
thanks for your answer.
