### ISSUE TITLE
Unmounted should cleanup effects

### ISSUE THREAD

**Issue by mote-ice** [vuejs/devtools-next#356]
如果我先 挂载一个 组件，卸载之后再挂载另一个组件之后 vite-plugin-vue-devtools 就会在控制台输出错误：Cannot read properties of undefined (reading 'api')；

![image](https://github.com/vuejs/devtools-next/assets/21765389/fd428016-fbb7-41ee-aa7a-9812071d9679)

[复现链接：](https://codesandbox.io/p/devbox/fu-xian-vite-plugin-vue-devtools-wen-ti-8ffthk?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clvlrwomc00073p6gcw1btwez%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clvlrwomc00023p6ghxhrz952%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clvlrwomc00043p6gnr0h1hel%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clvlrwomc00063p6gr3xp0y66%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clvlrwomc00023p6ghxhrz952%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvlrwomb00013p6g5yd0121r%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clvlrwomc00023p6ghxhrz952%2522%252C%2522activeTabId%2522%253A%2522clvlrwomb00013p6g5yd0121r%2522%257D%252C%2522clvlrwomc00063p6gr3xp0y66%2522%253A%257B%2522id%2522%253A%2522clvlrwomc00063p6gr3xp0y66%2522%252C%2522activeTabId%2522%253A%2522clvlshq2t012f3p6ge9le21cb%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A5173%252C%2522taskId%2522%253A%2522pnpm%2520run%2520dev%2522%252C%2522id%2522%253A%2522clvlshq2t012f3p6ge9le21cb%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clvlrwomc00043p6gnr0h1hel%2522%253A%257B%2522id%2522%253A%2522clvlrwomc00043p6gnr0h1hel%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvlrwomc00033p6gx7ibsjsd%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522pnpm%2520run%2520dev%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clvlrwomc00033p6gx7ibsjsd%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by alexzhang1030** [comment]
Apologies, the fix conflicts with the backward compatibility of the plugin API. Let's hold off on fixing it until the communication capabilities are redesigned.

**Comment by webfansplz** [comment]
Fixed in v7.3.0
