### ISSUE TITLE
[FEATURE MISSING] VUEX store integration missing

### ISSUE THREAD

**Issue by hassan-index** [vuejs/devtools-next#365]
I am unable to find the Vuex store as I'm using Vue 3.3.7 and Vuex 4.0.2. For just that I have to switch to a Chrome extension to view it.

**Comment by webfansplz** [comment]
We have PR to support it, https://github.com/vuejs/devtools-next/pull/289 

/cc @Azurewarth0920 I think we can move on now.

**Comment by hassan-index** [comment]
Well, I will be waiting for this PR to be merged.

**Comment by hassan-index** [comment]
@webfansplz Thanks for merging this PR [289](https://github.com/vuejs/devtools-next/pull/289)
