### ISSUE TITLE
Visual Studio Code - Insiders 中运行项目却是使用Visual Studio Code打开代码文件

### ISSUE THREAD

**Issue by fuxichen** [vuejs/devtools-next#366]
环境：windows，同时安装了 `vscode` 和 `vscode - Insiders`
1. 使用`vscode - Insiders`打开并运行项目
2. 在浏览器中点击组件跳转代码后使用的是vscode打开了对应组件的代码文件

**Comment by alexzhang1030** [comment]
See: https://devtools-next.vuejs.org/guide/faq#i-can-t-use-the-open-in-editor-feature

**Comment by alexzhang1030** [comment]
Duplicate of #341
