### ISSUE TITLE
feat: `LAUNCH_EDITOR` env support

### ISSUE THREAD

**Issue by webfansplz** [vuejs/devtools-next#369]
Add an option to configure the `open-in-editor` target IDE (maybe named `launchEditor`), make the feature easier to use and configure.

Be related to:

#125 #185 #341 #366 #367 

Refer to: 

https://github1s.com/yyx990803/launch-editor/blob/master/packages/launch-editor/guess.js#L17-L18

**Comment by Smef** [comment]
To add some context to this, the LAUNCH_EDITOR env is being overwritten upstream in [vite-plugin-vue-inspector](https://github.com/webfansplz/vite-plugin-vue-inspector). The launchEditor option being added here helps work around this, but the change to allow the env to be respected needs to happen in the other package. [PR here](https://github.com/webfansplz/vite-plugin-vue-inspector/pull/93). This is affecting Nuxt Devtools as well.

**Comment by Smef** [comment]
It looks like devtools-next is also overwriting the default, so it was being forced to "code" in both packages. I'm submitting  a PR for this one as well.
