### ISSUE TITLE
EACCES: permission denied, scandir '/.fseventsd'

### ISSUE THREAD

**Issue by caomeibuaichibaicai** [vuejs/devtools-next#384]
"vite": "^3.2.10",
"vite-plugin-vue-devtools": "^7.1.3",
本地启动报错，
` ERROR  19:10:52 [vite] Internal server error: EACCES: permission denied, scandir '/.fseventsd'         19:10:52
  Plugin: vite:import-glob`
使用sudo无效果

**Comment by webfansplz** [comment]
尝试升级 Vite 版本看看

**Comment by rrd108** [comment]
I run into this also

```bash
yarn dev
yarn run v1.22.22
$ vite

  VITE v3.2.10  ready in 484 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  Vue DevTools: Open http://localhost:5173/__devtools__/ as a separate window
  ➜  Vue DevTools: Press Alt(⌥)+Shift(⇧)+D in App to toggle the Vue DevTools

17:01:14 [vite] Internal server error: EACCES: permission denied, scandir '/lost+found'
  Plugin: vite:import-glob
  File: /home/rrd/public_html/laksmi3/node_modules/vite-plugin-vue-devtools/src/overlay.js?__vue-devtools-next-resource
```

**Comment by webfansplz** [comment]
> I run into this also
> 
> vite-plugin-vue-devtools: 7.4.4
> 
> ```shell
> yarn dev
> yarn run v1.22.22
> $ vite
> 
>   VITE v3.2.10  ready in 484 ms
> 
>   ➜  Local:   http://localhost:5173/
>   ➜  Network: use --host to expose
>   ➜  Vue DevTools: Open http://localhost:5173/__devtools__/ as a separate window
>   ➜  Vue DevTools: Press Alt(⌥)+Shift(⇧)+D in App to toggle the Vue DevTools
> 
> 17:01:14 [vite] Internal server error: EACCES: permission denied, scandir '/lost+found'
>   Plugin: vite:import-glob
>   File: /home/rrd/public_html/laksmi3/node_modules/vite-plugin-vue-devtools/src/overlay.js?__vue-devtools-next-resource
> ```

I think it has to do with the compatibility of the lower version of Vite, can you try to upgrade the Vite?

**Comment by rrd108** [comment]
I upgraded to vite 5.3.1 and it solved the issue.

Thanks
