### ISSUE TITLE
Support for Custom IDE in Element Selection

### ISSUE THREAD

**Issue by gmirmand** [vuejs/devtools-next#385]
Hello,

First of all, thank you for the excellent work on vuejs/devtools-next. It's an incredibly valuable tool for the Vue.js community.

I am currently facing a 'issue' with the feature that allows selecting an element on the page and opening it directly in the IDE. By default, this feature opens the element in Visual Studio Code. However, my preferred IDE is WebStorm. When Visual Studio Code is uninstalled, the feature does not function, and attempting to open the element in WebStorm results in an error:

```
Could not open <file> in the editor.
The editor process exited with an error: spawn code ENOENT.
```

It would be helpful if there could be support for using default IDE for this feature

Thank you for considering this enhancement and for your continued excellent work on this essential tool !

**Comment by webfansplz** [comment]
We'll ship `launchEditor` option in the next version, it'll allow users to configure the specified editor. 

See #373

**Comment by gmirmand** [comment]
Fabulous ! Thank you for the quick response and for adding the launchEditor option. Looking forward to the next version :)
