### ISSUE TITLE
the latest version is 7.1.3,but the document sad "Starting from v7.2.0, you can specify the editor by launchEditor option:"

### ISSUE THREAD

**Issue by chow5566** [vuejs/devtools-next#387]
When will version 7.2.0 be available？Sorry, I'm just anxious to know. When i use this in my webstorm,it throws a problem:"'code' is not recognized as an internal or external command,
operable program or batch file." and "Could not open WelcomeItem.vue in the editor.
The editor process exited with an error: (code 1).
"

![image](https://github.com/vuejs/devtools-next/assets/36839540/79a24346-4f92-4c2d-ab3e-ea797550561b)

**Comment by chow5566** [comment]
I finally know how to use it.like this:

`VueDevTools({
    componentInspector: {
      launchEditor: 'webstorm',
    }
  })`

**Comment by webfansplz** [comment]
V7.2.0 is released, you can use the `launchEditor` option direction now:

```ts
VueDevTools({ launchEditor: 'webstorm' })
```
