### ISSUE TITLE
本地开发，路由切换，路由无法跳转，路由守卫正常工作，但 js文件无法请求到，页面一直处于卡顿(loading)状态。但注释掉插件后，路由跳转正常。

### ISSUE THREAD

**Issue by mzc9915** [vuejs/devtools-next#392]
1. 环境：
包管理工具：pnpm
{
    "dependencies": {
        "vite": "5.2.11",
        "vue": "3.4.15",
        "vue-router": "4.2.5",
    },
    "devDependencies":{
        "vite-plugin-vue-devtools": "^7.2.0",
    }    
}。

2. vite.config.ts:
    plugins: [
        VueDevTools()
]
![image](https://github.com/vuejs/devtools-next/assets/50267789/c9b0788a-cb00-43ba-b80a-2adae2b502a9)

**Comment by mzc9915** [comment]
![Uploading WechatIMG24.jpg…]()

**Comment by qqqqww1** [comment]
同样的问题

![image](https://github.com/vuejs/devtools-next/assets/25215847/6ef145c7-dadf-4d26-9d33-ed08455fd30b)

![image](https://github.com/vuejs/devtools-next/assets/25215847/7408eec8-fab0-46f0-8369-757e8b1a72b0)

Router.beforeEach 被调用了两次，在移除Vue devtools之后就恢复了正常

**Comment by qqqqww1** [comment]
版本与 @mzc9915 所说的差不多
vue 3.4.27（尝试过3.3.0）
vue-router 4.2.5 
vue-devtools 7.2.0

同时尝试了降级vue-devtools到7.0.27，不起作用

**Comment by webfansplz** [comment]
方便提供一下最小可复现 Demo 吗？🙏

**Comment by Leovenn** [comment]
从7.1.3升级到最新版 7.2.0

![image](https://github.com/vuejs/devtools-next/assets/57058087/174af172-cb08-4843-b3cc-9f5082794b67)
![image](https://github.com/vuejs/devtools-next/assets/57058087/3b983b80-f598-4597-95ec-b9394cc67a20)

会加载两遍

加载两遍之后router.push 报错

![image](https://github.com/vuejs/devtools-next/assets/57058087/39d0bc65-afcb-4ff1-b8a8-afeb28bbb1e4)

使用最新版浏览器插件 或者 降级到7.1.3中 没有这个问题

当我使用干净的项目启动时(7.2.0)，无法复现

**Comment by Leovenn** [comment]
@webfansplz

**Comment by mzc9915** [comment]
我尝试使用 stackblitz 去构建一个相同的环境相同依赖的小 demo，但它似乎没有复现我的问题。 我目前的项目依赖内网环境，所以没办法分拆小demo。 但我刚才尝试，在 页面卡住时，按 F8 进入调试模式，发现代码阻塞的位置，如图 1：
![Snipaste_2024-05-17_15-34-43](https://github.com/vuejs/devtools-next/assets/50267789/e0150e1a-3714-40af-af5c-3ad30903a321)

source路径为：http://localhost:5173/node_modules/.pnpm/@vue+devtools-core@7.2.0_vite@5.2.11+vue@3.4.15/node_modules/@vue/devtools-core/dist/index.js?v=3044aefa。 

我尝试 F10调试时，如图2， 代码一直阻塞在红框位置。
![Snipaste_2024-05-17_15-36-52](https://github.com/vuejs/devtools-next/assets/50267789/a8040a4f-1210-446e-96ce-f9b9b4f5cff7)


不知道提供这些信息，是否有帮助

**Comment by Leovenn** [comment]
> 方便提供一下最小可复现 Demo 吗？🙏

我在我本地试图复现，但是无法复现，代码无法公开，如果您方便，可以加个v来远程看

**Comment by webfansplz** [comment]
@qqqqww1 @mzc9915 @Leovenn 请问下 V7.1.3 都是没问题的吗？

**Comment by mzc9915** [comment]
我7.1.3 和 7.2.0 都存在这个问题。 刚尝试了一下 7.1.3 版本，也是同样的问题。 我看了一下 pnpm.lock.yaml 文件里的信息，

<img width="1087" alt="image" src="https://github.com/vuejs/devtools-next/assets/50267789/36314428-b280-4715-ba5a-3ffc600e5815">

虽然 vite-plugin-vue-devtools 版本是 7.1.3，但它的依赖装了7.2.0，不知道是否影响。

**Comment by mzc9915** [comment]
本地安装了 旧版 6.6.1，但我昨天出问题后，已将 旧插件禁用了。
<img width="406" alt="image" src="https://github.com/vuejs/devtools-next/assets/50267789/6903bd34-6d63-430b-9b5e-6b232cc66489">

**Comment by webfansplz** [comment]
> 本地安装了 旧版 6.6.1，但我昨天出问题后，已将 旧插件禁用了。 <img alt="image" width="406" src="https://private-user-images.githubusercontent.com/50267789/331522627-6903bd34-6d63-430b-9b5e-6b232cc66489.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5Mzg3NDcsIm5iZiI6MTcxNTkzODQ0NywicGF0aCI6Ii81MDI2Nzc4OS8zMzE1MjI2MjctNjkwM2JkMzQtNmQ2My00MzBiLTliNWUtNmIyMzJjYzY2NDg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDA5MzQwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmM2FiNzIzNzMyNTc0YTAzMWJkNWFjOTAwNDFkNDA0MTI3MDM3Y2NiM2NjNjU2Y2NlMGJjYTFhOTI5NzBhMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8j5Q27cCI0snHQY_cXMkHRfJRcuc8w5j5M3rUjBQv70">

旧插件禁用后还会有问题吗

**Comment by mzc9915** [comment]
1. 我指定安装的 vite-plugin-vue-devtools 的版本是 7.1.3，版本没问题
<img width="952" alt="image" src="https://github.com/vuejs/devtools-next/assets/50267789/cf7cb8a8-5cbb-46eb-b6f0-381b9bb9d54c">

2. 旧插件是禁用的，不管是在 7.1.3 还是 7.2.0，都存在相同的问题；

**Comment by webfansplz** [comment]
我无法复现，应该是使用到了 Vue Router 的某个 API 触发了这个边界 Bug。还是要尽量提供下可复现辅助排查 🙏

**Comment by mzc9915** [comment]
我也是这样判断的。 我这边 再排查一下我的路由守卫这块的代码。 感谢你的回复，如后续有复现demo，我及时反馈。再次感谢你的回复。 🙏🙏🙏

**Comment by BryanAdamss** [comment]
相同问题!!!!!

**Comment by ah-kevin** [comment]
相同问题!!!!!

**Comment by webfansplz** [comment]
@BryanAdamss @ah-kevin 有报错吗？还是只是页面卡住无法跳转，可以的话帮忙看能否提供最小复现 🙏

**Comment by webfansplz** [comment]
Who can provide the configuration of vue-router in the project 🙏?

**Comment by webfansplz** [comment]
还有一个可以帮忙提供的有用信息：

步骤：关闭 DevTools Vite Plugin 插件，打开原先的 DevTools 浏览器扩展。这个问题是否也存在（有利于排查是 Vue Router DevTools Plugin 自身实现有问题还是新的 Vite Plugin 有问题）

**Comment by Leovenn** [comment]
> 还有一个可以帮忙提供的有用信息：
> 
> 步骤：关闭 DevTools Vite Plugin 插件，打开原先的 DevTools 浏览器扩展。这个问题是否也存在（有利于排查是 Vue Router DevTools Plugin 自身实现有问题还是新的 Vite Plugin 有问题）

![image](https://github.com/vuejs/devtools-next/assets/57058087/afde7f60-b6fb-4e1d-8385-e38bce5d4885)

当我使用DevTools 浏览器扩展 一切正常

**Comment by webfansplz** [comment]
> > 还有一个可以帮忙提供的有用信息：
> > 步骤：关闭 DevTools Vite Plugin 插件，打开原先的 DevTools 浏览器扩展。这个问题是否也存在（有利于排查是 Vue Router DevTools Plugin 自身实现有问题还是新的 Vite Plugin 有问题）
> 
> ![image](https://private-user-images.githubusercontent.com/57058087/331759581-afde7f60-b6fb-4e1d-8385-e38bce5d4885.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5OTk2NzksIm5iZiI6MTcxNTk5OTM3OSwicGF0aCI6Ii81NzA1ODA4Ny8zMzE3NTk1ODEtYWZkZTdmNjAtYjZmYi00ZTFkLTgzODUtZTM4YmNlNWQ0ODg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDAyMjkzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhYjg4M2I1M2Q5OTUyZjAwZmYwYWRkNDE0YWViN2YyZTEzMjU1OGJiOTc5OTZkZjg4OGE5ZDM1OWQ4YmQyZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zYP7ge8m7vdqUqzk_SJy0q60lCpy6s2lKnfqg0aHaqk)
> 
> 当我使用DevTools 浏览器扩展 一切正常

可否帮忙提供一下 Vue Router 的配置信息

**Comment by Leovenn** [comment]
> > > 还有一个可以帮忙提供的有用信息：
> > > 步骤：关闭 DevTools Vite Plugin 插件，打开原先的 DevTools 浏览器扩展。这个问题是否也存在（有利于排查是 Vue Router DevTools Plugin 自身实现有问题还是新的 Vite Plugin 有问题）
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/57058087/331759581-afde7f60-b6fb-4e1d-8385-e38bce5d4885.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5OTk2NzksIm5iZiI6MTcxNTk5OTM3OSwicGF0aCI6Ii81NzA1ODA4Ny8zMzE3NTk1ODEtYWZkZTdmNjAtYjZmYi00ZTFkLTgzODUtZTM4YmNlNWQ0ODg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDAyMjkzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhYjg4M2I1M2Q5OTUyZjAwZmYwYWRkNDE0YWViN2YyZTEzMjU1OGJiOTc5OTZkZjg4OGE5ZDM1OWQ4YmQyZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zYP7ge8m7vdqUqzk_SJy0q60lCpy6s2lKnfqg0aHaqk)
> > 当我使用DevTools 浏览器扩展 一切正常
> 
> 可否帮忙提供一下 Vue Router 的配置信息

我的路由是动态路由 如果您方便 可以远程调试

**Comment by webfansplz** [comment]
> > > > 还有一个可以帮忙提供的有用信息：
> > > > 步骤：关闭 DevTools Vite Plugin 插件，打开原先的 DevTools 浏览器扩展。这个问题是否也存在（有利于排查是 Vue Router DevTools Plugin 自身实现有问题还是新的 Vite Plugin 有问题）
> > > 
> > > 
> > > ![image](https://private-user-images.githubusercontent.com/57058087/331759581-afde7f60-b6fb-4e1d-8385-e38bce5d4885.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5OTk2NzksIm5iZiI6MTcxNTk5OTM3OSwicGF0aCI6Ii81NzA1ODA4Ny8zMzE3NTk1ODEtYWZkZTdmNjAtYjZmYi00ZTFkLTgzODUtZTM4YmNlNWQ0ODg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDAyMjkzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhYjg4M2I1M2Q5OTUyZjAwZmYwYWRkNDE0YWViN2YyZTEzMjU1OGJiOTc5OTZkZjg4OGE5ZDM1OWQ4YmQyZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zYP7ge8m7vdqUqzk_SJy0q60lCpy6s2lKnfqg0aHaqk)
> > > 当我使用DevTools 浏览器扩展 一切正常
> > 
> > 
> > 可否帮忙提供一下 Vue Router 的配置信息
> 
> 我的路由是动态路由 如果您方便 可以远程调试

是通过 addRoute 动态添加的吗？

**Comment by Leovenn** [comment]
> > > > > 还有一个可以帮忙提供的有用信息：
> > > > > 步骤：关闭 DevTools Vite Plugin 插件，打开原先的 DevTools 浏览器扩展。这个问题是否也存在（有利于排查是 Vue Router DevTools Plugin 自身实现有问题还是新的 Vite Plugin 有问题）
> > > > 
> > > > 
> > > > ![image](https://private-user-images.githubusercontent.com/57058087/331759581-afde7f60-b6fb-4e1d-8385-e38bce5d4885.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5OTk2NzksIm5iZiI6MTcxNTk5OTM3OSwicGF0aCI6Ii81NzA1ODA4Ny8zMzE3NTk1ODEtYWZkZTdmNjAtYjZmYi00ZTFkLTgzODUtZTM4YmNlNWQ0ODg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDAyMjkzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhYjg4M2I1M2Q5OTUyZjAwZmYwYWRkNDE0YWViN2YyZTEzMjU1OGJiOTc5OTZkZjg4OGE5ZDM1OWQ4YmQyZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zYP7ge8m7vdqUqzk_SJy0q60lCpy6s2lKnfqg0aHaqk)
> > > > 当我使用DevTools 浏览器扩展 一切正常
> > > 
> > > 
> > > 可否帮忙提供一下 Vue Router 的配置信息
> > 
> > 
> > 我的路由是动态路由 如果您方便 可以远程调试
> 
> 是通过 addRoute 动态添加的吗？

是的

**Comment by Leovenn** [comment]
我想我应该找到问题了 

复现步骤

 "element-plus": "^2.7.2",
 "vue": "^3.4.27",
 "vue-router": "^4.3.2"
  autoImport({
        resolvers: [ElementPlusResolver({ importStyle: "sass" })],
        dts: "src/typings/auto-imports.d.ts",
        include: [/\.tsx?$/, /\.vue$/],
        
 components({
        resolvers: [
          ElementPlusResolver({ importStyle: "sass" })
        
在页面中使用  v-loading 指令

![image](https://github.com/vuejs/devtools-next/assets/57058087/1e93d83b-8ab5-4546-9de6-a4e6481d831d)

会有重复的路由

不需要动态路由

@webfansplz

**Comment by webfansplz** [comment]
> 我想我应该找到问题了
> 
> 不需要动态路由
> 
> 复现步骤
> 
> "element-plus": "^2.7.2", "vue": "^3.4.27", "vue-router": "^4.3.2" autoImport({ resolvers: [ElementPlusResolver({ importStyle: "sass" })], dts: "src/typings/auto-imports.d.ts", include: [/.tsx?$/, /.vue$/],
> 
> components({ resolvers: [ ElementPlusResolver({ importStyle: "sass" })
> 
> 在页面中使用 element-plus组件 然后在组件中使用 v-loading 指令
> 
> ![image](https://private-user-images.githubusercontent.com/57058087/331763444-1e93d83b-8ab5-4546-9de6-a4e6481d831d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwMDQ4NTIsIm5iZiI6MTcxNjAwNDU1MiwicGF0aCI6Ii81NzA1ODA4Ny8zMzE3NjM0NDQtMWU5M2Q4M2ItOGFiNS00NTQ2LTlkZTYtYTRlNjQ4MWQ4MzFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDAzNTU1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiYmZkYTgxZDIwZjM5ZGQzMTNlMDJiZmZiZjZjMTkxZDAzMDIwYzdkMjdjNWE1ZTI2ZTk0MTMwN2IzYzFiYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MzkxXmSOpwE1i0sW9sfOlHyF0nx0PYnv7yg3V_xAW_I)
> 
> 会有重复的路由
> 
> @webfansplz

非常感谢，可以提供一个 github demo 复现仓库吗 🙏

**Comment by Leovenn** [comment]
各位是不是 在路由的页面中 使用的是  ep组件  并且在这个ep组件中使用了 v-loading指令
@mzc9915 @qqqqww1 @ah-kevin @BryanAdamss

**Comment by Leovenn** [comment]
> > 我想我应该找到问题了
> > 不需要动态路由
> > 复现步骤
> > "element-plus": "^2.7.2", "vue": "^3.4.27", "vue-router": "^4.3.2" autoImport({ resolvers: [ElementPlusResolver({ importStyle: "sass" })], dts: "src/typings/auto-imports.d.ts", include: [/.tsx?$/, /.vue$/],
> > components({ resolvers: [ ElementPlusResolver({ importStyle: "sass" })
> > 在页面中使用 element-plus组件 然后在组件中使用 v-loading 指令
> > ![image](https://private-user-images.githubusercontent.com/57058087/331763444-1e93d83b-8ab5-4546-9de6-a4e6481d831d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwMDQ4NTIsIm5iZiI6MTcxNjAwNDU1MiwicGF0aCI6Ii81NzA1ODA4Ny8zMzE3NjM0NDQtMWU5M2Q4M2ItOGFiNS00NTQ2LTlkZTYtYTRlNjQ4MWQ4MzFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDAzNTU1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiYmZkYTgxZDIwZjM5ZGQzMTNlMDJiZmZiZjZjMTkxZDAzMDIwYzdkMjdjNWE1ZTI2ZTk0MTMwN2IzYzFiYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MzkxXmSOpwE1i0sW9sfOlHyF0nx0PYnv7yg3V_xAW_I)
> > 会有重复的路由
> > @webfansplz
> 
> 非常感谢，可以提供一个 github demo 复现仓库吗 🙏

可以 您稍等下 我重新建立一个项目 然后在给您地址

**Comment by Leovenn** [comment]
> > 我想我应该找到问题了
> > 不需要动态路由
> > 复现步骤
> > "element-plus": "^2.7.2", "vue": "^3.4.27", "vue-router": "^4.3.2" autoImport({ resolvers: [ElementPlusResolver({ importStyle: "sass" })], dts: "src/typings/auto-imports.d.ts", include: [/.tsx?$/, /.vue$/],
> > components({ resolvers: [ ElementPlusResolver({ importStyle: "sass" })
> > 在页面中使用 element-plus组件 然后在组件中使用 v-loading 指令
> > ![image](https://private-user-images.githubusercontent.com/57058087/331763444-1e93d83b-8ab5-4546-9de6-a4e6481d831d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwMDQ4NTIsIm5iZiI6MTcxNjAwNDU1MiwicGF0aCI6Ii81NzA1ODA4Ny8zMzE3NjM0NDQtMWU5M2Q4M2ItOGFiNS00NTQ2LTlkZTYtYTRlNjQ4MWQ4MzFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDAzNTU1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiYmZkYTgxZDIwZjM5ZGQzMTNlMDJiZmZiZjZjMTkxZDAzMDIwYzdkMjdjNWE1ZTI2ZTk0MTMwN2IzYzFiYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MzkxXmSOpwE1i0sW9sfOlHyF0nx0PYnv7yg3V_xAW_I)
> > 会有重复的路由
> > @webfansplz
> 
> 非常感谢，可以提供一个 github demo 复现仓库吗 🙏

https://github.com/Leovenn/vite-devtools-bug

**Comment by briantang1117** [comment]
"vite-plugin-vue-devtools": "^7.2.0",
    "vant": "^4.9.0",
    "vue": "^3.4.27",
    "vue-router": "^4.3.2"
    "vite": "^5.2.11",
一样的问题 当vant使用过函数引入的toast后就不能跳转了 还以为是vant有问题 同样的__navigationId报错

**Comment by pangujs** [comment]
相同问题
"vite-plugin-vue-devtools": "^7.2.0",
"vue": "^3.4.27",
"vue-router": "^4.3.2"
"element-plus": "^2.7.3",
"vite": "^5.2.11",

不使用v-loading 或者 不使用vite-plugin-vue-devtools，问题消失。。。。

**Comment by webfansplz** [comment]
可以升级到 V7.2.1 看看，应该修复了

**Comment by pangujs** [comment]
> 可以升级到 V7.2.1 看看，应该修复了

7.2.1 已修复

**Comment by Leovenn** [comment]
谢谢🙏  7.2.1 已修复

**Comment by codeflyA** [comment]
遇到了同样的问题 7.2.1 已修复

**Comment by 946759113** [comment]
7.3.0 遇到同样问题，7.2.1没问题

**Comment by webfansplz** [comment]
> 7.3.0 遇到同样问题，7.2.1没问题

感谢反馈 🙏，可以试一下 7.3.1 是否正常。

**Comment by 946759113** [comment]
感谢🙏 7.3.1 已修复
