### ISSUE TITLE
Too long data in pinia store cannot use ui button

### ISSUE THREAD

**Issue by SkywalkerJi** [vuejs/devtools-next#417]
The current ui button (edit,add,etc) is located to the right of the data in the state.
 If the data string is very long, the ui button will be outside the screen and cannot be used.

**Comment by alexzhang1030** [comment]
Hi, can you upload a screenshot here?

**Comment by dvogelg4al** [comment]
Came here for the same issue, here's a screenshot: 
![Screenshot 2024-06-03 143233](https://github.com/vuejs/devtools-next/assets/134928350/8f834b21-09ed-4e78-95f0-58d80dc8a69f)

**Comment by dvogelg4al** [comment]
Thanks!
