### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by rubjo** [vuejs/devtools-next#420]
Anyone else getting these?

<img width="1053" alt="SCR-20240603-rdfz" src="https://github.com/vuejs/devtools-next/assets/42270947/06978a09-8eed-4ba3-98a6-60045ac74018">

App / browser freezes after activating DevTools and clicking on a few components in the Component Inspector in a PrimeVue 4 beta / Vue-Router / Pinia / vue-i18n app.

In the process of disabling / enabling one by one component / library to try to find out what's causing it.

**Comment by webfansplz** [comment]
Can you provide a mini repo? Thank you.

**Comment by rubjo** [comment]
Some digging was necessary here. I made a repo as minimal as I could (https://github.com/rubjo/primevue-4) and opened an issue with PrimeVue: https://github.com/primefaces/primevue/issues/5825.

**Comment by rubjo** [comment]
(not sure whether this is a PrimeVue issue or an issue of DevTools lacking failsafes against certain components)

**Comment by webfansplz** [comment]
Thanks for the feedback, I'll check it out and try to avoid devtools crashes caused by edge cases.

**Comment by alexzhang1030** [comment]
[Trace-01.json](https://github.com/user-attachments/files/15675793/Trace-01.json)

<img width="1764" alt="image" src="https://github.com/vuejs/devtools-next/assets/49969959/073989c4-b83b-42b5-94d5-3a70bea6ce04">


Here is a trace log of this reproduction bug, looks like `decode` was called in an infinite loop.

**Comment by alexzhang1030** [comment]
I confirmed this is a bug in the `encode` function that does not handle the circle referred object properly.

**Comment by rubjo** [comment]
7.5.2 here, also still have the issue.

**Comment by alexzhang1030** [comment]
Hi, can you share a minimal reproduction? I believe this might is another reason.

**Comment by rubjo** [comment]
@alexzhang1030 Thanks for being on the ball! 👍🏻 Updating to yesterday's 7.5.3 fixed it for me. #638?

**Comment by felix-berlin** [comment]
I'm encountering the same issue over and over again. Would like to share a minimal reproduction, but I can't because this happens in a private repo.
