### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'api')

### ISSUE THREAD

**Issue by Lazy-Hand** [vuejs/devtools-next#425]
``  const appLoading = createApp(AppLoading)
  appLoading.mount('#appLoading')
  const app = createApp(App)
  appLoading.unmount()
  app.mount('#app')``
index.js?v=fc2c00c9:4404 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'api')
    at Object.set (index.js?v=fc2c00c9:4404:36)
    at setActiveAppRecord (index.js?v=fc2c00c9:3089:29)
    at async index.js?v=fc2c00c9:4506:7

**Comment by webfansplz** [comment]
Duplicated #356, We've fixed it in v7.3.0. Let's wait for the release. (You can also try v7.3.0-beta.1 now)

**Comment by webfansplz** [comment]
Fixed in v7.3.0
