### ISSUE TITLE
Make selected component accessible via browser console

### ISSUE THREAD

**Issue by aflatscher-loop** [vuejs/devtools-next#426]
The old vue devtools (browser plugin) allowed to access the currently selected component instance via `$vm` in the browser console. This was quite handy if you wanted to trigger some exposed functions or similar.  Are there any plans on bringing this feature back?

<img width="915" alt="image" src="https://github.com/vuejs/devtools-next/assets/117654977/b9739397-9c60-4bb4-9890-abcd4f440864">

**Comment by webfansplz** [comment]
Good catch. I'll check it out when I have time, and if anyone is interested, PR is Welcome.
