### ISSUE TITLE
DevTools Pages show "0 routes registered in your application"

### ISSUE THREAD

**Issue by EnlonW** [vuejs/devtools-next#438]
![image](https://github.com/vuejs/devtools-next/assets/85759660/8500c5e2-2560-4115-9748-b0d00b7e21bd)
My web application has many routes, not zero. DevTools version v7.2.1.

**Comment by alexzhang1030** [comment]
Are there any error logs in your browser console?

**Comment by webfansplz** [comment]
Can you provide a mini repo? Thanks 🙏

**Comment by EnlonW** [comment]
> Can you provide a mini repo? Thanks 🙏

I am trying to create a mini repo

**Comment by EnlonW** [comment]
![image](https://github.com/vuejs/devtools-next/assets/85759660/151c87a0-6e4c-4a89-a76d-74297f1ae6bf)
Found a solution, but why are there multiple App here?

**Comment by webfansplz** [comment]
> ![image](https://private-user-images.githubusercontent.com/85759660/338795481-151c87a0-6e4c-4a89-a76d-74297f1ae6bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNjQ2ODcsIm5iZiI6MTcxODE2NDM4NywicGF0aCI6Ii84NTc1OTY2MC8zMzg3OTU0ODEtMTUxYzg3YTAtNmU0Yy00YTg5LWE3NmQtNzQyOTdmMWFlNmJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDAzNTMwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2ZGY4ZTE1N2VkNjQ5OTQ2MmUzNmMxZTc1N2ViOTI4M2FiNTZhYWZlZmU1NjE2YTZjYTQ3ODkyZTQyMzg1MzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qgl1XTJPrf4Su2L_Oq-7t0mOLxXlq8DTbXb45PTYUfE) Found a solution, but why are there multiple App here?

Did you use some global components from third-party libraries? They achieve functionality by creating Vue app instances.

**Comment by EnlonW** [comment]
> > ![image](https://private-user-images.githubusercontent.com/85759660/338795481-151c87a0-6e4c-4a89-a76d-74297f1ae6bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNjQ2ODcsIm5iZiI6MTcxODE2NDM4NywicGF0aCI6Ii84NTc1OTY2MC8zMzg3OTU0ODEtMTUxYzg3YTAtNmU0Yy00YTg5LWE3NmQtNzQyOTdmMWFlNmJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDAzNTMwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2ZGY4ZTE1N2VkNjQ5OTQ2MmUzNmMxZTc1N2ViOTI4M2FiNTZhYWZlZmU1NjE2YTZjYTQ3ODkyZTQyMzg1MzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qgl1XTJPrf4Su2L_Oq-7t0mOLxXlq8DTbXb45PTYUfE) Found a solution, but why are there multiple App here?
> 
> Did you use some global components from third-party UI libraries? They achieve functionality by creating Vue app instances.

Yes, I used the third-party UI libraries, thank you for telling me why
