### ISSUE TITLE
operation not permitted, scandir

### ISSUE THREAD

**Issue by Halecoder** [vuejs/devtools-next#444]
![image](https://github.com/vuejs/devtools-next/assets/75030331/a4b59495-8bc2-4073-b84f-83fed952e158)

[vite] Internal server error: EPERM: operation not permitted, scandir 'D:\System Volume Information'
  Plugin: vite:import-glob
  File: D:/Web/Java projects/WJ-Writer/node_modules/vite-plugin-vue-devtools/src/overlay.js

**Comment by Halecoder** [comment]
By the way, my project is electron

**Comment by alexzhang1030** [comment]
What's your vite version?

**Comment by Halecoder** [comment]
> What's your vite version?

I've tested a lot of versions with this issue，Not sure if it's my issue? I changed it to "@vue/devtools" according to the documentation, and it worked very well, but "vite-plugin-vue-devtools" will report an error in the image, which is strange, and it doesn't work when I update the dependency

**Comment by Halecoder** [comment]
I am using vite-plugin-vue-devtools version 7.0.17, however, I think it is my problem and I am ready to close this issue, thank you for your good work
