### ISSUE TITLE
Unable to inspect dynamically added Vue instances?

### ISSUE THREAD

**Issue by jeffwcx** [vuejs/devtools-next#449]
codesandbox：[devtools-dynamic-instance](https://codesandbox.io/p/github/jeffwcx/devtools-dynamic-instance/main)
git repo: [devtools-dynamic-instance](https://github.com/jeffwcx/devtools-dynamic-instance)

Encapsulate the `TheWelcome` component into a function call pattern

<img width="473" alt="image" src="https://github.com/vuejs/devtools-next/assets/14073775/77545486-a26f-428e-a5a3-f797317d473c">

Clicking the welcome button will dynamically create a new Vue instance and mount it in the DOM. In this case, the devtools are unable to inspect it.

**Comment by webfansplz** [comment]
Duplicated of #445, Let's track in here.

**Comment by jeffwcx** [comment]
> Duplicated of #445, Let's track in here.

Is this feature already in the development plan, or is it still a long way off?

**Comment by webfansplz** [comment]
> Is this feature already in the development plan, or is it still a long way off?

Vue only triggers `app:init` devtools hook when calling `createApp` function, we need to discuss and weigh how to handle this case.
