### ISSUE TITLE
Pinia inspector: edit property is not available for longer values

### ISSUE THREAD

**Issue by nuno-am** [vuejs/devtools-next#455]
### Vue devtools version
7.2.1

### Screenshots
https://github.com/vuejs/devtools-next/assets/99328312/5cb874fb-c06d-4bdd-82f1-5384e6ec7bdf

### What is expected?
On the Pinia store inspector, properties with longer values (longer than the available space) do not display their edit menu.
For such cases, the context menu should overlap the value content, in order to have it always available.

### Workaround
The root object can be edited as a JSON object. Properties that require change can be edited there, but it's as practical as editing individually.

**Comment by Azurewarth0920** [comment]
The long value should be trimmed to fit to the viewport size.

I'll fix it later.

**Comment by alexzhang1030** [comment]
Probably related to #419 /cc @Azurewarth0920

**Comment by alexzhang1030** [comment]
@nuno-am Please upgrade to v7.3.0 and check it out again, thank you!

**Comment by alexzhang1030** [comment]
duplicated of #417

**Comment by webfansplz** [comment]
Fixed in v7.3.0

**Comment by nuno-am** [comment]
Sorry for the late response, @alexzhang1030 and @webfansplz.
Yes, the issue seems to be fixed. However, for smaller displays, it might not be too easy to find out how to edit the properties, as the buttons could stay out of the visible area and need to be scrolled.

For all intents and purposes, I can consider the issue as fixed, but you should be aware of this limitation (check attached video).
Thanks!

https://github.com/vuejs/devtools-next/assets/99328312/3f2af94d-0cff-4f16-aa4d-698f27cddc92

**Comment by alexzhang1030** [comment]
> Sorry for the late response, @alexzhang1030 and @webfansplz. Yes, the issue seems to be fixed. However, for smaller displays, it might not be too easy to find out how to edit the properties, as the buttons could stay out of the visible area and need to be scrolled.
> 
> For all intents and purposes, I can consider the issue as fixed, but you should be aware of this limitation (check attached video). Thanks!
> 
>  Screen.Recording.2024-06-21.at.09.40.00.mov

We have discussed this earlier, and this is the final trade-off length. Maybe in the future, the max length will be configurable.
