### ISSUE TITLE
Seperate window cannot sync state with floating panel 

### ISSUE THREAD

**Issue by sxcooler** [vuejs/devtools-next#458]
I created a new vue project following the [Quick Start Guide](https://vuejs.org/guide/quick-start.html) using pnpm, js & vite.
When I opened a Chrome tab against http://localhost:5173/ , I found that the old devtools (chrome extension) is not working, instead, a new devtools shown as a float panel.
Here's the issue: I cancelled the tick on setting "Always show the floating panel" & closed the floating panel, and it never shown again, no matter I checked "Always show the floating panel" on or not ( in seperated tab of http://localhost:5173/__devtools__/)

![image](https://github.com/vuejs/devtools-next/assets/3192045/a830a3fa-db25-4252-a078-b1e83e5299ff)

![image](https://github.com/vuejs/devtools-next/assets/3192045/1e5264a7-d307-44aa-b8b6-dcd044b3b660)

I've tried refresh page / restart dev server / click "Reset Local Settings & State" button,  but still, the floating panel doesn't show.

But the keyboard shortcut shift + alt + d is still working, it can recover the floating panel button.
Use browser's "clear site data" can recover floating panel button too.

vue: 3.4.27
vite: 5.2.13
vite-plugin-vue-devtools: 7.2.1
Chrome: 125.0.6422.142

**Comment by alexzhang1030** [comment]
This is what the feature does exactly. If you disable Always Show the Floating Panel, you can only activate it using shortcuts.

Are you confused about the description?

**Comment by sxcooler** [comment]
> This is what the feature does exactly. If you disable Always Show the Floating Panel, you can only activate it using shortcuts.
> 
> Are you confused about the description?

I mean, when I check "Always show the floating panel" again, it doesn't show anyway.

**Comment by alexzhang1030** [comment]
https://github.com/vuejs/devtools-next/assets/49969959/19143ede-a4e8-41ac-86f6-e27965f39fb0

Sorry, I cannot reproduce it, what's your devtools version && browser version?

**Comment by sxcooler** [comment]
> Untitled.mp4 
> Sorry, I cannot reproduce it, what's your devtools version && browser version?

This is what exactly I said, u can't get this panel (or the button) shown again without using shortcut.

What I expect is, when I check this option on in seperate devtools window, the button would show, at least would show after refresh.


https://github.com/vuejs/devtools-next/assets/3192045/effd4d2a-680b-4030-a6ee-156cb2cc7a09

**Comment by alexzhang1030** [comment]
I guess its a separate window issuse, will take a look later

**Comment by sxcooler** [comment]
> Can not reproduce with these steps. 🤔 [#458 (comment)](https://github.com/vuejs/devtools-next/issues/458#issuecomment-2175682321)
> 
> The options are synchronized by localStorage internally. It means, at least the state should be synchronized when refreshing the page.
> 
> @sxcooler Can you clean your localStorage and try it again?

I've already tried that, by using Chrome's DevTools - Application - Storage - Clear site data, this did re-open floating panel (with light theme)

![image](https://github.com/vuejs/devtools-next/assets/3192045/d7f0184f-f6fd-40c8-80e2-f9ce0f7d0ce1)
