### ISSUE TITLE
Install error on Microsoft Edge/在Microsoft Edge上安装失败

### ISSUE THREAD

**Issue by L0st1** [vuejs/devtools-next#470]
## Problem
I open this link `https://chromewebstore.google.com/detail/vuejs-devtools-beta/ljjemllljcmogpfapbkkighbhhppjdbg?hl=zh-CN&utm_source=ext_sidebar` and install extension.
But I cant start this extension because` 此扩展包含恶意软件。` (This extension contains malicious software) 

![image](https://github.com/vuejs/devtools-next/assets/64479959/24523cc1-12c4-42c7-aa15-98d97f304b0b)

## Version
- 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0'
- win10

But the problem won't occur on Chrome.
Thanks for your time

**Comment by alexzhang1030** [comment]
It’s difficult to identify the exact issue. I have already reported this problem to the Edge team.

https://github.com/MicrosoftDocs/edge-developer/issues/3205

**Comment by clarancedsz** [comment]
It looks like you've installed the beta version of the Vue.js devtools. Beta versions are primarily for testing new features and may have bugs, but they aren't inherently vulnerable to attacks., it's recommended to switch to the stable version. Here is the link for Vue.js devtools by vuejs.org:
https://chromewebstore.google.com/detail/vuejs-devtools/nhdogjmejiglipccpnnnanhbledajbpd?hl=en

Follow me on Github;
https://github.com/clarancedsz

**Comment by L0st1** [comment]
> It looks like you've installed the beta version of the Vue.js devtools. Beta versions are primarily for testing new features and may have bugs, but they aren't inherently vulnerable to attacks., it's recommended to switch to the stable version. Here is the link for Vue.js devtools by vuejs.org: https://chromewebstore.google.com/detail/vuejs-devtools/nhdogjmejiglipccpnnnanhbledajbpd?hl=en
> 
> Follow me on Github; https://github.com/clarancedsz

Thanks for reply.You're right, but I'd rather try the beta version

**Comment by L0st1** [comment]
> It’s difficult to identify the exact issue. I have already reported this problem to the Edge team.
> 
> [MicrosoftDocs/edge-developer#3205](https://github.com/MicrosoftDocs/edge-developer/issues/3205)

Thank you for your help. Have a nice day

**Comment by webfansplz** [comment]
Hi @L0st1, Can you try again?

**Comment by alexzhang1030** [comment]
It appears to have been a false positive, and the issue was resolved after sending an email. Works on my local.

**Comment by L0st1** [comment]
> It appears to have been a false positive, and the issue was resolved now. Works on my local.

Yes, it is working now

**Comment by alexzhang1030** [comment]
Thanks for reporting!
