### ISSUE TITLE
enhance: display default page instead select view (save one extra click )

### ISSUE THREAD

**Issue by reslear** [vuejs/devtools-next#473]
instead:
<img width="767" alt="Screenshot 2024-06-24 at 17 17 30" src="https://github.com/vuejs/devtools-next/assets/12596485/288f8c30-0f79-43d5-aad9-d097ab05c87f">

display store by default: 
<img width="640" alt="Screenshot 2024-06-24 at 17 18 34" src="https://github.com/vuejs/devtools-next/assets/12596485/c330eafd-7d76-45ad-94e2-745f37d8f2a9">

**Comment by webfansplz** [comment]
Thanks for the feedback. It in our plans.
