### ISSUE TITLE
Whether the logo of vue-i18n should be changed?

### ISSUE THREAD

**Issue by LukerSpringtree** [vuejs/devtools-next#475]
<img width="842" alt="image" src="https://github.com/vuejs/devtools-next/assets/9697295/4973fa98-b152-4ab1-8cbd-ee0da5ba2264">

I know this icon is vue-i18n official icon. But it doesn't go with the whole style. 
It looks like a UI error with a bolder border width.
Let's change an icon to adapt, an icon like this:

<img width="108" alt="image" src="https://github.com/vuejs/devtools-next/assets/9697295/692d1d58-0996-4ca3-9fb3-bbf37f52b4b9">

**Comment by reslear** [comment]
I think you should write https://github.com/intlify/vue-i18n 
not here, as your intuitive sense should match the site.

**Comment by alexzhang1030** [comment]
Thats because: 
https://github.com/intlify/vue-i18n/blob/master/packages/vue-i18n-core/src/devtools.ts#L61

**Comment by alexzhang1030** [comment]
Sorry for closing its issue cause the vue-i18n defines the icon.
