### ISSUE TITLE
Lacks certain components on Component page

### ISSUE THREAD

**Issue by wjp980108** [vuejs/devtools-next#480]
Question 1: pinia function is gone, you can view it before
Question 2: when choosing a component with an arrow, you can't choose the component at all. after checking it through the component, you can recognize it. 7 components?
![1719277344366](https://github.com/vuejs/devtools-next/assets/54931083/3c79a14a-ed7a-49d2-b74d-ac8784dcee81)
![1719277626286](https://github.com/vuejs/devtools-next/assets/54931083/a8cd98ea-b6c8-4ea7-b5d3-1931456b4742)

**Comment by alexzhang1030** [comment]
Can you please provide a minimal reproduction? Thanks 😊

**Comment by wjp980108** [comment]
> Can you please provide a minimal reproduction? Thanks 😊
When I tried to reproduce the issue, I only encountered Problem 1. I'm not sure if Problem 2 didn't occur because I didn't use the router.
https://stackblitz.com/edit/vitejs-vite-yedtwk?file=src%2Fcomponents%2Ftest.vue,src%2Fcomponents%2FNaiveProvider%2Findex.vue,src%2FApp.vue&terminal=dev

**Comment by wjp980108** [comment]
When I click Components, I warned me
![image](https://github.com/vuejs/devtools-next/assets/54931083/e2e79e7e-0022-4d5d-91cd-cea4c426f476)


> > Can you please provide a minimal reproduction? Thanks 😊
> 
> When I tried to reproduce the issue, I only encountered Problem 1. I'm not sure if Problem 2 didn't occur because I didn't use the router. https://stackblitz.com/edit/vitejs-vite-yedtwk?file=src%2Fcomponents%2Ftest.vue,src%2Fcomponents%2FNaiveProvider%2Findex.vue,src%2FApp.vue,package.json&terminal=dev

**Comment by alexzhang1030** [comment]
> > Can you please provide a minimal reproduction? Thanks 😊
> 
> When I tried to reproduce the issue, I only encountered Problem 1. I'm not sure if Problem 2 didn't occur because I didn't use the router. [stackblitz.com/edit/vitejs-vite-yedtwk?file=src%2Fcomponents%2Ftest.vue,src%2Fcomponents%2FNaiveProvider%2Findex.vue,src%2FApp.vue,package.json&terminal=dev](https://stackblitz.com/edit/vitejs-vite-yedtwk?file=src%2Fcomponents%2Ftest.vue,src%2Fcomponents%2FNaiveProvider%2Findex.vue,src%2FApp.vue,package.json&terminal=dev)

Pinia functions are hosted by `pinia` package, you can use pinia store after installing it.

**Comment by wjp980108** [comment]
> > > Can you please provide a minimal reproduction? Thanks 😊
> > 
> > 
> > When I tried to reproduce the issue, I only encountered Problem 1. I'm not sure if Problem 2 didn't occur because I didn't use the router. [stackblitz.com/edit/vitejs-vite-yedtwk?file=src%2Fcomponents%2Ftest.vue,src%2Fcomponents%2FNaiveProvider%2Findex.vue,src%2FApp.vue,package.json&terminal=dev](https://stackblitz.com/edit/vitejs-vite-yedtwk?file=src%2Fcomponents%2Ftest.vue,src%2Fcomponents%2FNaiveProvider%2Findex.vue,src%2FApp.vue,package.json&terminal=dev)
> 
> ![image](https://private-user-images.githubusercontent.com/49969959/342566928-a2bd276e-2497-4a7d-8ce4-aad1d59c83b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyODY3NTcsIm5iZiI6MTcxOTI4NjQ1NywicGF0aCI6Ii80OTk2OTk1OS8zNDI1NjY5MjgtYTJiZDI3NmUtMjQ5Ny00YTdkLThjZTQtYWFkMWQ1OWM4M2IwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDAzMzQxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1MGQyNzg1NWJkYzFhMzM2MDI2NmI4NzY4YTllOTdlMjQzOTdjNjk3YzQ2YTI1M2YyYzE0NGM1NWMzOWUwZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AZZAu4V7t-aPKVCEDLvPB3OVHVz_enVLoOMlChsnf9s)
> 
> Pinia functions are hosted by `pinia` package, you can use pinia store after installing it.

Sorry, I forgot to install Pinia in an example

**Comment by wjp980108** [comment]
I found a problem
Incorrect
![image](https://github.com/vuejs/devtools-next/assets/54931083/43816431-16f6-4e3c-8b4a-bdd45e46a827)
correct
![image](https://github.com/vuejs/devtools-next/assets/54931083/2f3c4ebc-5023-47eb-a469-0ccddc7908a3)
