### ISSUE TITLE
Extension Devtools does not work with multi-app on chrome v126

### ISSUE THREAD

**Issue by pikax** [vuejs/devtools-next#492]
the main app is not detected when using this approach to create a new app:

```bash
pnpm vite create
# chose vue -> javascript
```

```js
// composables/container.js
import {  createApp } from "vue";

function buildContainer() {
  const container = document.createElement("div");
  container.id = "dialog-container";
  container.className =
    "absolute top-0 left-0 pointer-events-none w-full h-full flex ";
  return container;
}
export function createNewApp(_app) {
  const container = buildContainer();

  const app = createApp({
    render: () => {
      // render stuff
    },
  });
  // copy provides
  Object.entries(_app._context.provides).forEach(([k, v]) => app.provide(k, v));
  app.mount(container);
  return {
    // ...

    render() {
      document.body.appendChild(container);
    },
  };
}

// main.js

import { createApp } from 'vue'
import './style.css'
import App from './App.vue'
import { createNewApp } from './composables/container'

const app = createApp(App);

createNewApp(app).render();
app.mount('#app')
````

**Comment by Lootjs** [comment]
Which devtools are you using, plugin, extension, or standalone?

**Comment by pikax** [comment]
Chrome extension

**Comment by Lootjs** [comment]
![image](https://github.com/vuejs/devtools-next/assets/16526639/218d2200-61a0-45d5-a159-accef5873a5f)
Couldn't reproduce. Could you try on another browser or on the plugin? 🤔

**Comment by pikax** [comment]
Here's the project https://stackblitz.com/edit/vitejs-vite-2w7ana?file=src%2Fmain.js,src%2Fcomposables%2Fcontainer.js&terminal=dev 



> Couldn't reproduce. Could you try on another browser or on the plugin? 🤔

What project are you using? The screenshot does not look like the repo I've provided, I can update the title to reflect better the specific issue I'm having, but the problem is still there even if it work on the plugin.

**Comment by pikax** [comment]
Seems like I didn't know the Vue button is the button to press to change App 😅  

Not a bug, it was my fault for not knowing the UX changes 😅 
![image](https://github.com/vuejs/devtools-next/assets/4620458/6ac4b79d-0913-447f-8755-ecc6d2e791b8)
