### ISSUE TITLE
in play.vuejs.org, no way debug my component

### ISSUE THREAD

**Issue by elonehoo** [vuejs/devtools-next#493]
i am not determine this is bug ? 

because i not methods debug my write component

<img width="1710" alt="image" src="https://github.com/vuejs/devtools-next/assets/43719490/fbaeaca2-a9c9-47a2-a9b3-95dc20fd21e2">

**Comment by webfansplz** [comment]
This is because devtools runs the `play.vue` vue app itself, rather than the Vue components running in the Vue REPL.

**Comment by elonehoo** [comment]
i recall being able to choose between 「App 1/App 2」 in the previous version, but i haven't come across this option since updating to version 6.0.

**Comment by elonehoo** [comment]
it have a chance to return?

**Comment by webfansplz** [comment]
> i recall being able to choose between 「App 1/App 2」 in the previous version, but i haven't come across this option since updating to version 6.0.

https://devtools-next.vuejs.org/getting-started/features#multiple-apps-support

However, this is unrelated to it. Vue REPL runs components in a specific way that devtools cannot recognize.

**Comment by elonehoo** [comment]
oh Nooooooooooooooooooo!

thank you!

**Comment by elonehoo** [comment]
i go to run `pnpm create vite my-vue-app --template vue-ts`
