### ISSUE TITLE
assets in duplicate paths between root and public will be divided into the same path in the assets tab

### ISSUE THREAD

**Issue by LoTwT** [vuejs/devtools-next#510]
# description

assets in duplicate paths between root and public will be divided into the same path in the assets tab

I'm not sure if this behavior is expected.

<img width="1547" alt="image" src="https://github.com/vuejs/devtools-next/assets/50254496/cc47598e-c06c-46e6-a622-cd0218cd5bcb">

reproduction URL: <https://stackblitz.com/edit/vitejs-vite-eonmde>

**Comment by alexzhang1030** [comment]
`public` is a special `directory`, maybe we can mark it in the UI to tell users this is a `public` directory.

**Comment by LoTwT** [comment]
> `public` is a special `directory`, maybe we can mark it in the UI to tell users this is a `public` directory.

Could it be better to distinguish public assets with the prefix `public` which may be `<somepath>/a.svg` and `public/<somepath>/b.svg`?

**Comment by alexzhang1030** [comment]
It's kinda counterintuitive yet designed, that's because we want to follow the behavior of `vite`. Most people are unlikely to encounter this situation. I think putting a badge on the public resources is a good solution now.

**Comment by LoTwT** [comment]
<img width="902" alt="image" src="https://github.com/vuejs/devtools-next/assets/50254496/7c80ea30-33c9-4390-9fe9-16a29449617d">

Do you think the grouping mode shown above is a good solution? If so, I will continue to change the list view, otherwise, adding a badge is better. Hope for your advice.

**Comment by alexzhang1030** [comment]
Hmm, it's good I think
