### ISSUE TITLE
The component search result tree immediately closes after finding the desired component.

### ISSUE THREAD

**Issue by slavarazum** [vuejs/devtools-next#515]
![CleanShot 2024-07-10 at 15 25 30](https://github.com/vuejs/devtools-next/assets/5820718/4532bfec-6b3f-47af-ac6f-aaa174cf6589)

>   System:
>     OS: macOS 14.5
>     CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
>     Memory: 83.17 MB / 16.00 GB
>     Shell: 5.9 - /bin/zsh
>   Binaries:
>     Yarn: 1.22.22 - /usr/local/bin/yarn
>     npm: 10.7.0 - ~/Library/Application Support/Herd/config/nvm/versions/node/v20.15.0/bin/npm
>     pnpm: 9.4.0 - /usr/local/bin/pnpm
>   Browsers:
>     Chrome: 126.0.6478.127
>     Safari: 17.5
>   npmPackages:
>     @vue/devtools: ^7.3.5 => 7.3.5 

Reproduces with in standalone app as well as Vite plugin.

**Comment by alexzhang1030** [comment]
I will track it

**Comment by alexzhang1030** [comment]
Hi, can you provide a minimal reproduction? I cannot reproduce it on my local.

**Comment by slavarazum** [comment]
Hey @alexzhang1030

Certainly! My fault, initially, I believed the issue persisted in a fresh install, but it turns out the problem is isolated to my logo component. 
Sandbox reproduction: https://stackblitz.com/edit/vitejs-vite-hfsdfn?file=src%2FLogo%2FQrutoLogo.vue

![CleanShot 2024-07-18 at 15 44 27](https://github.com/user-attachments/assets/f89bf9d8-73ae-44d7-bb39-0601d27961ae)

The issue appears on line 51 of the `QrutoLogo` component, where the `QLogo` component is embedded.
