### ISSUE TITLE
When using vite plugin, any way to launch a standalone window during chrome devtools DEVICE TOOLBAR?

### ISSUE THREAD

**Issue by Fnxxxxo** [vuejs/devtools-next#520]
I am now using device toolbar. When I open vue devtools, it is too small to check data. Any way to open a new window?

**Comment by Lootjs** [comment]
what is a device toolbar?🤔

**Comment by Lootjs** [comment]
uhh, I guess, you mean this mode 👀

![image](https://github.com/user-attachments/assets/173da855-06d0-420d-b469-a557c77c13d0)

**Comment by Lootjs** [comment]
It would be great if you use browser extensions instead of the plugin while the device toolbar is active 🤔

**Comment by Fnxxxxo** [comment]
> It would be great if you use browser extensions instead of the plugin while the device toolbar is active 🤔

But I cannot browse chrome store page. The CRX also cannot work in my chrome。

**Comment by Lootjs** [comment]
Have you tried https://devtools-next.vuejs.org/guide/standalone ?

**Comment by Fnxxxxo** [comment]
Nope. It requires some config in the index.html. I afraid one day I may push it online

**Comment by Lootjs** [comment]
Hmm you also can install any chromium browser (f.e [Chromium](https://www.chromium.org/getting-involved/download-chromium/)) then install the .crx file into the browser🤔
