### ISSUE TITLE
Unable to open component in editor while using browser extension

### ISSUE THREAD

**Issue by niksy** [vuejs/devtools-next#522]
Using latest Chrome extension version: https://chromewebstore.google.com/detail/vuejs-devtools-beta/ljjemllljcmogpfapbkkighbhhppjdbg?hl=en

Same functionality works with current stable version: https://chromewebstore.google.com/detail/vuejs-devtools/nhdogjmejiglipccpnnnanhbledajbpd?hl=en

Is there any option that needs to be set globally so this functionality is available? I see that there should be "Open in editor" button along with render code, DOM inspect and scroll to component actions.

**Comment by webfansplz** [comment]
Be related to https://github.com/vuejs/devtools-next/discussions/111#discussioncomment-9992959_ 

We'll support it.

**Comment by avxkim** [comment]
Missing it too, it was so convenient
