### ISSUE TITLE
Inspecting components served with Vike generate errors when trying to evaluate pageContext

### ISSUE THREAD

**Issue by pdanpdan** [vuejs/devtools-next#542]
Devtools tries to inspect `pageContext` by checking if some keys are present in the object, but the `pageContext` proxy is designed to assert/throw errors when access to unavailable properties is attempted.
Is there a way this can be solved on one side only or as a collaboration between `vike` and `vue devtools-next`?

ref https://github.com/vikejs/vike-vue/issues/160

**Reproduction:**

```bash
pnpm create bati --vue
```

then inspect `RootComponent/LayoutDefault/Sidebar/Link` (any of them)

**Comment by pdanpdan** [comment]
The component is simple:

```vue
<template>
  <a :class="{ active: isActive }">
    <slot />
  </a>
</template>

<script lang="ts" setup>
import { usePageContext } from "vike-vue/usePageContext";
import { computed, useAttrs } from "vue";

const pageContext = usePageContext();
const { href } = useAttrs();
const isActive = computed(() => {
  const { urlPathname } = pageContext;
  return href === "/" ? urlPathname === href : urlPathname.startsWith(href);
});
</script>
```

**Comment by alexzhang1030** [comment]
Can Vike identify the wrong access on the user side or devtools side?

**Comment by brillout** [comment]
@alexzhang1030 I ain't sure what you mean; let me elaborate what's going on here.

The [`pageContext` object](https://vike.dev/pageContext) is a global object containing information about the page. The user controls what `pageContext` properties are sent to the client (with the [`passToClient` setting](https://vike.dev/passToClient)). Now, if the user tries to access a property on the client-side that doesn't exist on the client-side then Vike throws this error: https://vike.dev/passToClient#error. (Failing early and hard is helpful for users.)

Now the [`pageContext` object is made `shallowReactive()`](https://github.com/vikejs/vike-vue/blob/3753d03c8fcfa8841a5a176e9e07f6acb1f74eab/packages/vike-vue/src/renderer/createVueApp.ts#L59). It seems like DevTools hooks itself and tries to read some properties on the `pageContext` that doesn't exist leading to the error I mentioned in my previous paragraph.

Is there a list of properties that DevTools tries to access that we can whitelist?

**Comment by alexzhang1030** [comment]
Thanks for the detailed description! 
Devtools will try to access an object's property to identify the object's type ( such as if [it's a Vue instance](https://github.com/vuejs/devtools-next/blob/main/packages/devtools-kit/src/core/component/state/is.ts#L2) or others).
Perhaps we can discuss a better solution.

**Comment by brillout** [comment]
Would it be possible for Vue DevTools to do this?

```diff
- if (object.someProp) {
+ if ('someProp' in object) {
    // ...
  }
```

That would [solve the problem](https://vike.dev/passToClient#error).

The properties DevTools tries to access are:

```js
[
  'render',
  '_',
  '__asyncLoader',
  'effect',
  'state',
  'currentRoute'
]
```

Vike could suppress the error for these properties, but that would be an issue for `state` because it's common for users to defined `pageContext.state`. (On a tangent, I also wonder whether it could cause an issue for DevTools when users define `pageContext.state`.)
