### ISSUE TITLE
Huge performance impact

### ISSUE THREAD

**Issue by KaelWD** [vuejs/devtools-next#548]
v6 was pretty bad on pages with lots of components but it didn't really matter until you activated the vue tab. v7 seems to be doing a bunch of work as soon as chrome devtools is opened, adding 100ms+ to every interaction.

This is me just scrolling through a list in the vuetify documentation in a fresh tab that hasn't used vue devtools yet:
![Screenshot_20240726_151448](https://github.com/user-attachments/assets/a9b3e40d-ea5d-43eb-aded-4d0ec489a9e2)
The green column is vue rendering in 3ms, all the purple is 140ms of vue devtools prepare.js.

**Comment by KaelWD** [comment]
I can't actually get v6 to have a noticeable impact on this page even with update tracking enabled, so v7 really is a huge step backwards currently.

**Comment by webfansplz** [comment]
We are about to optimize the initialization overhead of devtools to make it as on-demand as possible (before opening the devtools client). Additionally, we want to understand where v7's performance has not improved compared to v6 after opening the devtools client. We've done some work in this area, and if you could provide a small reproducible example to help us investigate this regression, it would be greatly appreciated.

**Comment by KaelWD** [comment]
This was https://github.com/vuetifyjs/vuetify

```
pnpm build vuetify api
pnpm dev docs
```

Then navigating through the first menu on http://localhost:8095/en/components/menus/ with the keyboard.

**Comment by alexzhang1030** [comment]
Related #211, probably serialize/deserialize
