### ISSUE TITLE
Select app interface optimization

### ISSUE THREAD

**Issue by BWrong** [vuejs/devtools-next#583]
The currently selected app is too deeply hidden, consider moving it to sidebar, like in 6.0

**Comment by BWrong** [comment]
- 6.0
<img width="311" alt="image" src="https://github.com/user-attachments/assets/f16d6c89-921f-4fee-8fbb-f53863b64922">
- 7.0
<img width="623" alt="image" src="https://github.com/user-attachments/assets/cc3a3335-ede2-4a21-901f-97d3acbb2511">

**Comment by webfansplz** [comment]
https://github.com/vuejs/devtools-next/commit/f6c9be537bf16be4d56e507e9421fc85878e4400

Released in v7.3.9

**Comment by BWrong** [comment]
> [f6c9be5](https://github.com/vuejs/devtools-next/commit/f6c9be537bf16be4d56e507e9421fc85878e4400)
> 
> 发布于 v7.3.9

When will browser extensions be supported?

**Comment by webfansplz** [comment]
> > [f6c9be5](https://github.com/vuejs/devtools-next/commit/f6c9be537bf16be4d56e507e9421fc85878e4400)
> > 发布于 v7.3.9
> 
> When will browser extensions be supported?

Yep, released in v7.0.0 beta 5
