### ISSUE TITLE
Could not open [idx].vue in the editor.

### ISSUE THREAD

**Issue by gewisser** [vuejs/devtools-next#587]
Hi all

It is unclear why the issue was closed: #534 

The problem exists and has not gone away:
https://github.com/yyx990803/launch-editor/blob/master/packages/launch-editor/index.js#L110

![image](https://github.com/user-attachments/assets/736bfdf1-a06c-491b-ba41-ec74c052406c)

### Trying to open file:
`C:\ProgramUser\ApacheDir\Ancor\frontend-app\src\pages\p2p\deals\[idx].vue`

Square brackets are not allowed in regular expression

![image](https://github.com/user-attachments/assets/c2bfdb13-be1f-49fb-806e-3ae0bdf4a75d)

```
"vite-plugin-vue-devtools": "^7.3.9"
"launch-editor-middleware": "^2.8.1",
```

**Comment by gewisser** [comment]
I think this regular expression check is completely unnecessary. It doesn't protect against anything.

https://github.com/vuejs/devtools-next/issues/531#issuecomment-2249212867
👆 I think it will be needed more than once... ))

**Comment by alexzhang1030** [comment]
That's interesting, can you file an issue on https://github.com/yyx990803/launch-editor this repo?

**Comment by gewisser** [comment]
> That's interesting, can you file an issue on https://github.com/yyx990803/launch-editor this repo?

Pull requests have been open for almost two weeks now.:
https://github.com/yyx990803/launch-editor/pull/75

**Comment by gewisser** [comment]
@alexzhang1030 fixed in v2.8.2

https://github.com/yyx990803/launch-editor/compare/v2.8.1...v2.8.2

**Comment by alexzhang1030** [comment]
Great, you can use it once Vite has been released by this https://github.com/vitejs/vite/pull/18039.

**Comment by webfansplz** [comment]
This issue will be fixed in the next Vite release version, so let's close it.

**Comment by gewisser** [comment]
My prayers were answered))

https://github.com/yyx990803/launch-editor/compare/v2.8.2...v2.9.1#diff-f3a5176348208fec4b413a18bea297e65643a3fffb7d64e0a6806f2d9d2cb764L110

**Comment by gewisser** [comment]
> This issue will be fixed in the next Vite release version, so let's close it.

After that, several releases came out. Now I updated everything to the latest versions, but no one updated the dependencies ((

![image](https://github.com/user-attachments/assets/2289a4f1-f8bf-40c6-87a8-e9bf1931a493)


![image](https://github.com/user-attachments/assets/16a250fa-c6fe-47c9-89f7-a531388134b3)

https://github.com/vitejs/vite/blob/v5.4.5/packages/vite/package.json#L125
