### ISSUE TITLE
[bug] When nuxt devtools is enabled, pinia logs "x store installed" are present

### ISSUE THREAD

**Issue by alSergey** [vuejs/devtools-next#593]
### 🐛 The bug

If nuxt devtools are enabled, then pinia "x store installed" logs appear in the console. The only way to disable them is to disable nuxt devtools.

The original example is in the [pinia repository](https://github.com/vuejs/pinia/issues/2749).

### 🛠️ To reproduce

https://stackblitz.com/edit/pinia-store-installed-repro?file=pages%2Findex.tsx

### 🌈 Expected behavior

There is a setting that allows to disable these logs.

### ℹ️ Additional context

I opened an [issue in the pinia repository](https://github.com/vuejs/pinia/issues/2749), they told me it was a problem with [nuxt devtools](https://github.com/nuxt/devtools).
After that, I opened an [issue in the nuxt devtools repository](https://github.com/nuxt/devtools/issues/718), they told me this is a problem in vue devtools.

**Comment by webfansplz** [comment]
https://github1s.com/vuejs/pinia/blob/v2/packages/pinia/src/devtools/plugin.ts#L319-L320

We need to support plugin setting feature to let users customize it.

**Comment by alSergey** [comment]
@webfansplz is there a workaround to disable these logs now? They really interfere with my work.
