### ISSUE TITLE
bug: maximum call stack 

### ISSUE THREAD

**Issue by reslear** [vuejs/devtools-next#605]
![CleanShot 2024-09-09 at 17 36 55@2x](https://github.com/user-attachments/assets/a0c86edb-5cc3-418b-b95d-b40ec4ecca10)

could be due to async persistedstate: https://github.com/soc221b/pinia-plugin-persistedstate-2

vue 5.5.3
devtools latest

**Comment by twisterniq** [comment]
I'm having the same issue but couldn't create a minimal reproduction. It starts with Vue version `3.5.0` and happens in every version up to 3.5.4. The console spam begins when I click the `Vue` tab in Developer Tools. It doesn't occur in `3.4.38`.

**Comment by webfansplz** [comment]
> I'm having the same issue but couldn't create a minimal reproduction. However, I’ve noticed a few things:
> 
> * The issue starts with Vue version `3.5.0` and persists through `3.5.4`.
> * It doesn't occur in version `3.4.38`.
> * The console spam begins after I open the `Vue` tab in Developer Tools.
> * If I open a new tab and do not click on the `Vue` tab, there’s no spam.
> * It is definitely related to Pinia.

Thanks for the feedback, could you also use https://github.com/soc221b/pinia-plugin-persistedstate-2?

**Comment by webfansplz** [comment]
> ![CleanShot 2024-09-09 at 17 36 55@2x](https://private-user-images.githubusercontent.com/12596485/365716253-a0c86edb-5cc3-418b-b95d-b40ec4ecca10.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMTEzOTEsIm5iZiI6MTcyNjExMTA5MSwicGF0aCI6Ii8xMjU5NjQ4NS8zNjU3MTYyNTMtYTBjODZlZGItNWNjMy00MThiLWI5NWQtYjQwZWM0ZWNjYTEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDAzMTgxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiZTFmMDM5M2VjY2JiYjQzMzQ5OTI1YThjZmQ2OTQ1NjkxMWM5NzZmNDQ1YTY1YjU3Y2VhZTRiOGIzMmUzMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dhJ8g0CH9Tyz7MbarHWXFSiNK0mbEZi54V1Xcw2pH0Y)
> 
> could be due to async persistedstate: https://github.com/soc221b/pinia-plugin-persistedstate-2
> 
> vue 5.5.3 devtools latest

I can not reproduce it, can you provide a mini repo? thanks.

**Comment by twisterniq** [comment]
> > I'm having the same issue but couldn't create a minimal reproduction. However, I’ve noticed a few things:
> > 
> > * The issue starts with Vue version `3.5.0` and persists through `3.5.4`.
> > * It doesn't occur in version `3.4.38`.
> > * The console spam begins after I open the `Vue` tab in Developer Tools.
> > * If I open a new tab and do not click on the `Vue` tab, there’s no spam.
> > * It is definitely related to Pinia.
> 
> Thanks for the feedback, could you also use https://github.com/soc221b/pinia-plugin-persistedstate-2?

I'm using https://github.com/prazdevs/pinia-plugin-persistedstate, but I tested without it as well, and the issue still persists.

**Comment by JeanFranz73** [comment]
having the same issue on a work project, without `pinia-plugin-persistedstate` plugin, can't show the code but trying to reproduce in a clean installation
![image](https://github.com/user-attachments/assets/bee9b462-21c5-46dd-a2e4-3af2df881892)

**Comment by webfansplz** [comment]
I'm not sure if it related to vue, can someone upgrade to vue 3.5.5 and try again?

**Comment by twisterniq** [comment]
> I'm not sure if it related to vue, can someone upgrade to vue 3.5.5 and try again?

I´ve just tried it and the issue is still happening.

**Comment by webfansplz** [comment]
> > I'm not sure if it related to vue, can someone upgrade to vue 3.5.5 and try again?
> 
> I´ve just tried it and the issue is still happening.

Can you help to provide a mini repo? 🙏

**Comment by reslear** [comment]
It’s strange that there’s no such issue in the minimal reproduction.

Could someone fork it and add some details closer to your product?

https://stackblitz.com/edit/vitejs-vite-uiu4uu?file=src%2Fcomponents%2FHelloWorld.vue

**Comment by twisterniq** [comment]
I tried to create a minimal reproduction, but at this point I still don't know what exactly is causing the issue. I'll try to do some more tests when I have more time.

**Comment by eneeio-nm** [comment]
I'm getting the same - and I'm using the Beta version of the Chrome Extension:

![screenshot-2024-09-16--15 42 49@2x](https://github.com/user-attachments/assets/0d5bb603-b31f-4869-aad3-bffe5729901c)

I don't have `pinia-plugin-persistedstate`. I do use `pinia` and also TanStack Query Devtools.

**Comment by webfansplz** [comment]
> I'm getting the same - and I'm using the Beta version of the Chrome Extension:
> 
> ![screenshot-2024-09-16--15 42 49@2x](https://private-user-images.githubusercontent.com/127733587/367804162-0d5bb603-b31f-4869-aad3-bffe5729901c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3NTYwMzMsIm5iZiI6MTcyNjc1NTczMywicGF0aCI6Ii8xMjc3MzM1ODcvMzY3ODA0MTYyLTBkNWJiNjAzLWIzMWYtNDg2OS1hYWQzLWJmZmU1NzI5OTAxYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOVQxNDIyMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hODJjODg1NWIwNDRhNDEwMmRhNDgwYzQ3NmM4ZTczMGU4ODJhY2VmZDQ2ZmI1ZWUyZWNlMjk5YzRmZWYyOTBjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Cvj3oE1DJ4S413XEp_FiduON0mwprmtHYrKh6_NC6nE)
> 
> I don't have `pinia-plugin-persistedstate`. I do use `pinia` and also TanStack Query Devtools.
> 
> Other packages include:
> 
> ```
>     "pinia": "2.2.2",
>     "primevue": "4.0.7",
>     "vue": "3.5.6",
>     "vue-i18n": "10.0.1",
>     "vue-router": "4.4.5"
> ```

Can you provide a mini repo or share the repo to help we reproduce this issue? thanks 🙏

**Comment by reslear** [comment]
> > I'm getting the same - and I'm using the Beta version of the Chrome Extension:
> > ![screenshot-2024-09-16--15 42 49@2x](https://private-user-images.githubusercontent.com/127733587/367804162-0d5bb603-b31f-4869-aad3-bffe5729901c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3NTYwMzMsIm5iZiI6MTcyNjc1NTczMywicGF0aCI6Ii8xMjc3MzM1ODcvMzY3ODA0MTYyLTBkNWJiNjAzLWIzMWYtNDg2OS1hYWQzLWJmZmU1NzI5OTAxYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOVQxNDIyMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hODJjODg1NWIwNDRhNDEwMmRhNDgwYzQ3NmM4ZTczMGU4ODJhY2VmZDQ2ZmI1ZWUyZWNlMjk5YzRmZWYyOTBjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Cvj3oE1DJ4S413XEp_FiduON0mwprmtHYrKh6_NC6nE)
> > I don't have `pinia-plugin-persistedstate`. I do use `pinia` and also TanStack Query Devtools.
> > Other packages include:
> > ```
> >     "pinia": "2.2.2",
> >     "primevue": "4.0.7",
> >     "vue": "3.5.6",
> >     "vue-i18n": "10.0.1",
> >     "vue-router": "4.4.5"
> > ```
> 
> Can you provide a mini repo or share the repo to help we reproduce this issue? thanks 🙏

it's a bit complicated, how do you do a proper debug ?

**Comment by sacki5** [comment]
We are experiencing the same issue with our app
Works when downgrading to to vue@3.4.38

Also using:
* pinia
* vue-i18n
* vue-router
* tanstack/vue-query

**Comment by webfansplz** [comment]
> sacki5

I can not reproduce it. Can you help to provide a mini repo 🙏?

**Comment by webfansplz** [comment]
> We are experiencing the same issue with our app Works when downgrading to to vue@3.4.38
> 
> Also using:
> 
> * pinia
> * vue-i18n
> * vue-router
> * tanstack/vue-query
>   We are not using pinia persisted state
> 
> Not sure if it helps but sometimes I get another stack trace. <img alt="Screenshot 2024-09-27 at 10 39 08" width="597" src="https://private-user-images.githubusercontent.com/25466424/371458794-401d878e-4f2e-4ce4-b27d-12c8fe98e75e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MzgyNTYsIm5iZiI6MTcyNzQzNzk1NiwicGF0aCI6Ii8yNTQ2NjQyNC8zNzE0NTg3OTQtNDAxZDg3OGUtNGYyZS00Y2U0LWIyN2QtMTJjOGZlOThlNzVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDExNTIzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4YTIzYTRmM2FhZGUxNWI1YzZlZGI4NzE5ZTE1MGZkYjNkYjRmOWNmOGU3OTI3ZjQ3YjI5MmIwMTA2ZWMyNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Hxbqwhn30VUNTmru0WmD7S4mu-_4xhVeFt3Aj5E67Jg">

I can not reproduce it. Can you help to provide a mini repo 🙏?

**Comment by valtteriluomapareto** [comment]
This is also happening with latest Vue 3.5.10

Using also
- Pinia
- Vue-router
- Vue-i18n

Not using pinia persisted state. 

Not sure if this helps, but some of the stack traces were leading to setTimeouts. We have simple timeouts to mock API response lag when not developing against a real backend:

```ts
// This is just for dev purposes to simulate loading delay.
function delay(ms: number): Promise<void> {
  return new Promise<void>((resolve, reject) => {
    if (typeof ms !== 'number' || ms < 0) {
      reject(new Error('Delay must be a non-negative number.'))
    } else {
      setTimeout(resolve, ms)
    }
  })
}

...

const returnMockData = async () => {
  await delay(500)
  return [<mock data array>]
}
```

Sorry, don't have time to build reproduction repo atm.

**Comment by sacki5** [comment]
> > We are experiencing the same issue with our app Works when downgrading to to vue@3.4.38
> > Also using:
> > 
> > * pinia
> > * vue-i18n
> > * vue-router
> > * tanstack/vue-query
> >   We are not using pinia persisted state
> > 
> > Not sure if it helps but sometimes I get another stack trace. <img alt="Screenshot 2024-09-27 at 10 39 08" width="597" src="https://private-user-images.githubusercontent.com/25466424/371458794-401d878e-4f2e-4ce4-b27d-12c8fe98e75e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MzgyNTYsIm5iZiI6MTcyNzQzNzk1NiwicGF0aCI6Ii8yNTQ2NjQyNC8zNzE0NTg3OTQtNDAxZDg3OGUtNGYyZS00Y2U0LWIyN2QtMTJjOGZlOThlNzVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDExNTIzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4YTIzYTRmM2FhZGUxNWI1YzZlZGI4NzE5ZTE1MGZkYjNkYjRmOWNmOGU3OTI3ZjQ3YjI5MmIwMTA2ZWMyNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Hxbqwhn30VUNTmru0WmD7S4mu-_4xhVeFt3Aj5E67Jg">
> 
> I can not reproduce it. Can you help to provide a mini repo 🙏?

Haven't had time creating a mini repo yet. Also not sure what is causing it yet. Will try to create one as soon as I have more time.

**Comment by reslear** [comment]
we do have a problem because of https://github.com/wobsoriano/pinia-shared-state/issues/38 ?

**Comment by webfansplz** [comment]
If anyone is still experiencing this issue, any feedback and reproducible examples would be greatly appreciated. 🙏

**Comment by JeanFranz73** [comment]
I've tried in many different ways to reproduce the same error in another repo but I simply can't replicate the same behaviour. Can't share the project either because it's a private project from another company.

Here' the dependencies if someone has similar:
```
{
  "dependencies": {
    "apexcharts": "^3.54.1",
    "axios": "^1.7.7",
    "dayjs": "^1.11.13",
    "hls.js": "^1.5.17",
    "howler": "^2.2.4",
    "pinia": "^2.2.4",
    "v-calendar": "^3.1.2",
    "vue": "^3.5.12",
    "vue-my-toasts": "^2.0.1",
    "vue-router": "^4.4.5",
    "vue-the-mask": "^0.11.1",
    "vue3-apexcharts": "^1.7.0",
    "vuetify": "^3.7.3"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^4.6.2",
    "eslint": "^8.57.1",
    "eslint-plugin-vue": "^9.29.1",
    "sass": "1.78.0",
    "vite": "^4.5.5",
    "vite-plugin-vue-devtools": "^7.5.2",
    "vite-plugin-vuetify": "^2.0.4"
  }
}
```

Some details of the environment if it could help:

- Using Firefox 131.0.3;
- Using Bun 1.1.29;
- Running on Ubuntu 22.04 LTS;

The project also uses websockets, which maybe can affect in some way?

The error starts specifically when open the panel for the first time in the instance of the tab, and then piles up each time the mouse moves in different parts of this panel, like pinia, components, routes etc

If someone who has the same problem have dependendencies or another thing in common, post here, hope this helps

**Comment by webfansplz** [comment]
Try to fix it in v7.5.3 (vite plugin) and browser extension v7 beta.11 (pending review), if this issue has been resolved in the latest version, please let me know, thanks 🙏

**Comment by kelsos** [comment]
I am not getting the issue after updating to 7.5.3 so at least for my case the fix seems to work fine. Thank you very much @webfansplz

**Comment by twisterniq** [comment]
It is fixed for me too. Thanks @webfansplz!

**Comment by SionGrey** [comment]
Does not work without downgrading to vue 3.4.38 for us still. For those who got this fixed, can you post your versions of vue and pinia?

**Comment by webfansplz** [comment]
> Does not work without downgrading to vue 3.4.38 for us still. For those who got this fixed, can you post your versions of vue and pinia?

Hi, what’s your devtools version?

**Comment by SionGrey** [comment]
> Hi, what’s your devtools version?
I tried vite plugin 7.5.3 and chrome extension 7 beta 11

**Comment by webfansplz** [comment]
> > Hi, what’s your devtools version?
> 
> I tried vite plugin 7.5.3 and chrome extension 7 beta 11

I can't reproduce it. Could you provide a mini repo? Thanks. 🙏

**Comment by JeanFranz73** [comment]
> Does not work without downgrading to vue 3.4.38 for us still. For those who got this fixed, can you post your versions of vue and pinia?

For me it stays the same as above, pinia 2.2.4 and vue 3.5.12. Now working fine on Bun
