### ISSUE TITLE
Feature request: Events timeline panel

### ISSUE THREAD

**Issue by hakanedison** [vuejs/devtools-next#609]
We really need the Events panel to track Vue events (the list of emitted events and the properties of selected event).

See also #538.

Currently, that's the only reason we can't switch from version 6 to 7. We really need to, because in version 6, some of our components can't be inspected because of an hard-to-pinpoint flaw, in DevTools _or_ in our code).

Thanks for your great work!

**Comment by webfansplz** [comment]
Thank you for your feedback. We believe this feature request makes sense. Previously, we did not implement it due to significant performance overhead and memory leaks. However, if users truly need it, we should find a way to enable it on-demand (or have it disabled by default and allow users to enable it manually).

**Comment by yaffol** [comment]
I would also find the component events timeline very useful. I agree that making it an on-demand, or configurable option makes sense.

**Comment by mreduar** [comment]
It would be really useful to have it at least as an option to activate it momentarily. I am currently working on a bug that would make it much easier to see the events emitted.

**Comment by webfansplz** [comment]
Cooking 🧑‍🍳

<img width="889" alt="image" src="https://github.com/user-attachments/assets/e23ca5e2-09c6-4ff8-a888-7fa91abc0f77">

**Comment by webfansplz** [comment]
See you soon 😊

![timeline](https://github.com/user-attachments/assets/349afa7a-0af9-46d6-a33e-63a10b970633)

**Comment by mreduar** [comment]
> See you soon 😊
> 
Nice!

**Comment by hakanedison** [comment]
Great! 👍🏻

**Comment by rubjo** [comment]
Agreed – the current text is neither showing active state nor action, it's showing state if clicked 😄

**Comment by webfansplz** [comment]
Thanks for the feedback, I've submitted a PR to improve the UX about it.

**Comment by rubjo** [comment]
This still leaves room for confusion. I propose #642.
