### ISSUE TITLE
vite-plugin-vue-devtools disables browser devtools extension

### ISSUE THREAD

**Issue by Solant** [vuejs/devtools-next#613]
When `vite-plugin-vue-devtools` plugin is enabled, browser dev tools (https://addons.mozilla.org/en-US/firefox/addon/vue-js-devtools/) are disabled

I'm unsure if this is an expected behaviour, or some issue of having 2 instances simultaneously.

**Comment by webfansplz** [comment]
Yes, they're not compatible at the moment. If you use chrome or edge browser, we recommend using the v7 extension https://devtools-next.vuejs.org/guide/browser-extension (though we won't rule out releasing the firefox v7 extension at a later date)

**Comment by Solant** [comment]
Thanks for clarifying, have a nice day!
