### ISSUE TITLE
[Browser extension] Vue tab gets stuck on page-reload

### ISSUE THREAD

**Issue by sestriel** [vuejs/devtools-next#621]
Using Chrome Browser Extension ver. 7.0.0 beta 7, Chrome Version 129.0.6668.70 (Offizieller Build) (arm64), on MacBook M1.

So devtools-next works great, until you have to reload the page (or navigate through). Then it gets stuck on the "V" loading animation and i have to re-open chrome dev-tools or right-click in vue-tab and "reload frame". Then its working again, until next reload. 

Old/other Vue extensions are deleted, devtools-next is the only installed extension.

Could you please check this or can i do something about this?

**Comment by ryanalbrecht** [comment]
Can confirm I have the exact same issue.
