### ISSUE TITLE
Timeline panel doesn't work in the Chrome Extension

### ISSUE THREAD

**Issue by TheDutchCoder** [vuejs/devtools-next#634]
None of the events get recorded in the Chrome Extension version. Latest version is installed. (7.0.0 beta9)

**Comment by TheDutchCoder** [comment]
Ah, I didn't realize you had to click two buttons for this, I thought the record button would enable tracking and turning it off would, you know, disable it 😉 

But yes, it works if I enable it in 2 places.

**Comment by webfansplz** [comment]
Yes, It's a little bit of a chore, the design is mainly based on performance considerations. I'll explain it later in the documentation.
