### ISSUE TITLE
hide select component button on seperate window

### ISSUE THREAD

**Issue by mpcompany2024** [vuejs/devtools-next#639]
![Screenshot_1](https://github.com/user-attachments/assets/9a800734-129d-4dcf-924a-e045d1a7debd)
i can't not use select component with vite v5.4.9 and vite-plugin-vue-devtools 7.0.25

**Comment by duowb** [comment]
Because it is in a new page, you cannot use the selector function to select elements from other pages.

**Comment by webfansplz** [comment]
Yep, it's by design. See: https://github.com/vuejs/devtools-next/pull/541
