### ISSUE TITLE
New Devtools extension displays wrong Vue version

### ISSUE THREAD

**Issue by gespinha** [vuejs/devtools-next#640]
Hey everyone,

I've recently installed the new devtools extension (using version 7.0.0 beta 11) and my Vuejs version appears incorrectly.

This is what I have installed: 
![image](https://github.com/user-attachments/assets/b8e62367-d12c-4a37-8957-0afb4ccfb5de)

This is what I see:
![image](https://github.com/user-attachments/assets/2470e161-17b8-4a9f-b9a3-4907d70ba003)

Is this a known issue or is there anything I'm doing wrong?

Thanks!

**Comment by webfansplz** [comment]
Hi, can you check if there are multiple instances of Vue in your app, and they have different versions of Vue?

**Comment by duowb** [comment]
![image](https://github.com/user-attachments/assets/f5d91511-c54f-45c8-828e-5abcc7091e5d)

1. Select the root node
2. Print `$0.__vue_app__.version` in the console
