### ISSUE TITLE
dev tools crashing after hot realoding

### ISSUE THREAD

**Issue by lipecss** [vuejs/devtools-next#644]
I've been noticing that in all projects I work with vue, whether it's simple or complex when hot reloading the devtools is crashing and I need to click on the X and open it again.

So if I'm using vue store or pinia they disappear

![image](https://github.com/user-attachments/assets/fea2ba3d-ec6c-40af-b970-4bf2a291375e)

Version: 6 . 6 . 3

**Comment by webfansplz** [comment]
This is devtools v7 repository, v6-related issues can be submitted in this [repository](https://github.com/vuejs/devtools-v6), you can also try to use v7 (https://devtools-next.vuejs.org/guide/browser-extension)
